#### In this notebook, we take the categorised data frame created from the player match data and competition meta data and clean it. While cleaning, we also assess and explore data quality issues.

In [1]:
from pathlib import Path
import pandas as pd
import json

In [2]:
#Getting successfully scraped files

# read project folder (1 folder up from where we are right now)
data_collection = Path("../data_collection")

# read scrape log
log = pd.read_csv(data_collection / "scrape_log.csv")

#keeping only successful logs
log_success = log[log["status"] == "success"]

# getting file NAMES from the successful logs in a list [] called success_files
success_files = log_success["file_name"].tolist()

# we have the file names of success files. Now we want the actual files, not just the names. For that, we need to define the path for python.
json_folder = data_collection / "raw_match_centres" # note that raw_match_centre is where all your downloaded JSONs are from your scraper

# getting success files and saving them in a list called records
records = []

for file in success_files: #looping on each file in success_files 
    with open(json_folder / file, "r", encoding="utf-8") as f: #adding them here
        records.append(json.load(f))

# sanity check 
len(records)
# 21,027 success records out of 23,501 total scraped records.

21027

In [3]:
# creating data frame out of it


#creating empty rows for player-match dataset
player_rows = []

#labelling the data we need for each JSON in records
for record in records: #loop through each JSON (biggest loop)
    
    # READABILITY
    
    # Give shorter names to the relevant parts of the JSON
    fixture = record["fixture"] #now fixture dictionary in each JSON is called fixture
    tournament = record["tournament"] #now events list is called events in each JSON
    events = record["events"] #now tournament dictionary is called tournament

    # Combine both teams' player lists
    players = (
        record["team1_players"]
        + record["team2_players"]
    )

    # SUBSTITUTION LOGIC
    
    # Loop through every player listed for this match/this JSON
    for player in players:

        # If any player information is empty, flag it!
        t1_empty = len(record["team1_players"]) == 0
        t2_empty = len(record["team2_players"]) == 0
        one_team_empty = t1_empty != t2_empty # exactly one of the two teams has an empty player list

        # start by assuming the player did not come on as a substitute
        substituted = False

        # Check every event in this match
        for event in events:

            # assuming a type 4 event is a substitution, a type 2 is a goal.
            # assuming aiff_player_id is the player who came on and sub_aiff_player_id is the outgoing player
            if (
                event.get("type") == 4
                and event.get("aiff_player_id") == player.get("aiff_id")
            ): #if type = 4 and id is there,
                substituted = True #players gets us all players. this marks, which of those ends up actually coming onto field. later we see that for all (almost) status 1, subt is false and for 2, substitution is true some half, re-inforcing our logic of status and type both.
                break #if you find a match of substitution for this player, break this loop, don't check more events, go to appearance loop!

        # Build one player-match row
        row = {
            "match_id": fixture.get("id"),
            "competition_id": fixture.get("tournament_id"),
            "competition_name": fixture.get("tournament_name"),
            "match_date": fixture.get("date"),
            "match_venue": fixture.get("venue"),
            "match_stadium": fixture.get("stadium"),
            "ft": fixture.get("ft"),
            "ft_text": fixture.get("ft_text"),

            "team_type": tournament.get("team_type"),

            "player_name": player.get("player_name"),
            "player_id": player.get("player_id"),
            "player_aiff_id": player.get("aiff_id"),
            "player_team_id": player.get("team_id"),
            "status": player.get("status"),
            "one_team_player_data_missing": one_team_empty,

            "substituted": substituted,
        }

        # Add this row to the list
        player_rows.append(row)

# Convert all rows into a dataframe
player_matches = pd.DataFrame(player_rows)

In [4]:
# creating team ID - team name dataset from scraped records 
team_rows = []

for record in records:
    teams_data = record.get("teams_data", {})

    # Case 1: teams_data is a dictionary
    if isinstance(teams_data, dict):

        for team_id, team_info in teams_data.items():
            team_rows.append({
                "team_id": team_id,
                "team_name": team_info.get("name"),
                "team_short_name": team_info.get("short_name"),
            })

    # Case 2: teams_data is a list
    elif isinstance(teams_data, list):

        for team_info in teams_data:
            team_rows.append({
                "team_id": team_info.get("id")
                           or team_info.get("team_id"),
                "team_name": team_info.get("name")
                             or team_info.get("team_name"),
                "team_short_name": team_info.get("short_name"),
            })

team_lookup = pd.DataFrame(team_rows)

team_lookup["team_id"] = pd.to_numeric(
    team_lookup["team_id"],
    errors="coerce"
).astype("Int64")

team_lookup = (
    team_lookup
    .dropna(subset=["team_id"])
    .drop_duplicates()
)

team_name_conflicts = (
    team_lookup
    .groupby("team_id")["team_name"]
    .nunique()
    .sort_values(ascending=False)
)

team_lookup.to_csv("team_id_name_map.csv")

In [5]:
# merging team names with dataset
player_matches = player_matches.merge(
    team_lookup[["team_id", "team_name"]],
    how="left",
    left_on="player_team_id",
    right_on="team_id",
    validate="many_to_one",
).drop(columns="team_id")

In [64]:
# combining categorisations into our dataframe. Our big dataset with scraped data and categories is called df. Our analysis dataset will be called df_analysis. 

# getting csv with competition meta data made my AI + human
comp_categories = pd.read_csv("competitions_classified_AI_Human.csv")

# Keep only the metadata columns needed for analysis from the competition metadata dataset
competition_metadata = comp_categories[
    [
        "competition_name",
        "AI_level",
        "AI_state",
        "AI_age",
        "AI_primary_format_teams",
        "AI_gender"
    ]
]

# Merge competition metadata onto player-match dataset and create new dataset called player_matches_enriched
df = player_matches.merge(
    competition_metadata,
    on="competition_name",
    how="left",
    validate="many_to_one"
)

# Check merge
print(df.shape)
df.head()

(807367, 22)

,match_id,competition_id,competition_name,match_date,match_venue,match_stadium,ft,ft_text,team_type,player_name,...,player_team_id,status,one_team_player_data_missing,substituted,team_name,AI_level,AI_state,AI_age,AI_primary_format_teams,AI_gender
0,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Kabir Mehta,...,19665,1,False,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male
1,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Tavish Sharma,...,19665,2,False,True,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male
2,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Eklavya Choudhary,...,19665,3,False,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male
3,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Swastik Sharma,...,19665,1,False,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male
4,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Navya Mittal,...,19665,1,False,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male

In [7]:
# To confirm gender was correctly assigned.
# Show only competitions containing female-related keywords that are still labelled Male.

keywords = r"asmita|female|women|girl|girls|kanyashree"

(
    df.loc[df["AI_gender"] == "Male", "competition_name"]
      .drop_duplicates()
      .loc[
          lambda s: s.str.contains(
              keywords,
              case=False,
              na=False,
              regex=True
          )
      ]
      .sort_values()
)

7989       ASMITA FOOTBALL LEAGUE U-15 - 2024-25, BHAVNAGAR
120460         ASMITA FOOTBALL LEAGUE U-15 - 2024-25, SURAT
109685         ASMITA FOOTBALL LEAGUE U-17 - 2024-25, SURAT
467866    ASMITA Zonal Football League 2025-26,Karnataka...
503121    U -13 ASMITA Zonal Football League 2025-26, Ch...
196742    U 13 ASMITA City Football League 2025-26, Agar...
180493    U 13 ASMITA City football league 2025-26, Nara...
224401    U 13 ASMITA Football City/District League 2025...
698773    U 16 Asmita Football League 2025-26, Mancheria...
26467     U- 13 ASMITA Football League 2024- 25, Anantap...
261376    U-13 ASMITA CITY FOOTBALL LEAGUE 2025-2026 (Al...
439197    U-13 ASMITA CITY FOOTBALL LEAGUE 2025-2026 (BA...
447129    U-13 ASMITA CITY FOOTBALL LEAGUE 2025-2026 (Ja...
202664    U-13 ASMITA CITY FOOTBALL LEAGUE 2025-2026 = R...
167537    U-13 ASMITA CITY FOOTBALL LEAGUE 2025-26 BANGA...
461116                       U-13 ASMITA CITY LEAGUE SIKKIM
618960         U-13 ASMITA National Football League 2025-26
703971    U-16 ASMITA CITY FOOTBALL LEAGUE 2025-2026 (Ph...
670826    U-16 ASMITA CITY FOOTBALL LEAGUE 2025-2026 (Ub...
669994    U-16 ASMITA CITY FOOTBALL LEAGUE 2025-2026 = R...
669817                U-16 ASMITA CITY LEAGUE SIKKIM soreng
179538    U/13 ASMITA CITY FOOTBALL LEAGUE 2025-26,KAVRA...
176497    U13 ASMITA CITY FOOTBALL LEAGUE 2025-26, PONDI...
263035    U13 ASMITA City Football League 2025-26, Banas...
188765                 U13 ASMITA City League 2025-26,Delhi
8677      U13 ASMITA Football League 2024-25, Aizawl, Mi...
55580     U13 ASMITA Football League 2024-25, Prayagraj, UP
462907    U13 ASMITA city football league 2025-26 ( una,...
184910    U13 Asmita City Football League 2025-26, Jalga...
9045      U15 ASMITA Football League 2024-25, Aizawl, Mi...
39568      U15 ASMITA Football League 2024-25, Moradabad,UP
105192            U15 Asmita Football League 2024-25 Nazira
666126    U16 ASMITA City Football League 2025-26, Aizaw...
683505    U16 ASMITA City Football League 2025-26, Surat...
663184    U16 ASMITA Football League 2025-26, Agartala, ...
683140    U16 ASMITA Football League 2025-26, Belgaum, K...
687278    U16 ASMITA city football league 2025-26 ( una,...
691340    U16 Asmita City Football League 2025-26, Latur...
645352    U16 Asmita City Football League 2025-26, Raiga...
662684    U16 Asmita City Football League 2025-26, Ratna...
709355    U16 Asmita City Football League 2025-26, Sangl...
734781    U16 Asmita City Football League 2025-26, Solap...
66324     U17 ASMITA Football League 2024-25, Belgaum, K...
2383      U17 ASMITA Football League 2024-25, Madanapall...
454505    Under 13 ASMITA Zonal Football League 2025-26,...
665707        Under 16 ASMITA Football League 2026 - Kerala
Name: competition_name, dtype: str

In [8]:
# Manual classification overrides
# ASMITA competitions:
# Overrode AI gender classification to "Female" for competitions containing keywords such as "ASMITA", "Women's", "Girls", "Female", and "Kanyashree". These are AIFF/state women's competitions that the AI occasionally classified as Male because gender was not explicit in every competition name.

# Sanjeewan State Level U-12 and U-15 Football Tournaments (2025):
# Overrode competition format from "Club League" to "Other". Manual review confirmed these are pure knockout tournaments rather than league-format competitions, so they do not meet the study's definition of a Club League.
#manual fixes 
keywords = r"asmita|female|women|girl|girls|kanyashree"

# Manually classify obvious female competitions
df.loc[
    df["competition_name"].str.contains(
        keywords,
        case=False,
        na=False,
        regex=True
    ),
    "AI_gender"
] = "Female"

knockout_tournaments = [
    "Sanjeewan State Level U-15 Football Tournament 2025",
    "Sanjeewan State Level U-12 Football Tournament 2025",
]

df.loc[
    df["competition_name"].isin(knockout_tournaments),
    "AI_primary_format_teams"
] = "Other"

df.loc[
    df["competition_name"].isin([
        "Stay Your Age Cup - 2025",
        "JSW YOUTH CUP 2025 (UNDER -18)"
    ]),
    "AI_primary_format_teams"
] = "Other"

df.to_csv("scraped_categorised_data.csv")
len(df)

807367

In [9]:
# creating analysis dataset with Club Leagues, Male, Youth
df_analysis = df[
    (df["AI_primary_format_teams"] == "Club League") &
    (df["AI_gender"] == "Male") &
    (df["AI_age"] == "Youth")
].copy()

print(df_analysis.shape)
df_analysis.head()

(291844, 22)

,match_id,competition_id,competition_name,match_date,match_venue,match_stadium,ft,ft_text,team_type,player_name,...,player_team_id,status,one_team_player_data_missing,substituted,team_name,AI_level,AI_state,AI_age,AI_primary_format_teams,AI_gender
0,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Kabir Mehta,...,19665,1,False,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male
1,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Tavish Sharma,...,19665,2,False,True,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male
2,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Eklavya Choudhary,...,19665,3,False,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male
3,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Swastik Sharma,...,19665,1,False,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male
4,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Navya Mittal,...,19665,1,False,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male

In [66]:
df_analysis['AI_state'].value_counts()

AI_state
National            99871
West Bengal         31052
Goa                 29007
Maharashtra         24854
Karnataka           22811
Gujarat             16875
Delhi               12956
Kerala              11931
Rajasthan           10368
Himachal Pradesh     9250
Puducherry           7645
Assam                6886
Madhya Pradesh       2843
Punjab               1694
Chhattisgarh         1382
Odisha               1319
Manipur              1029
Tamil Nadu             41
Name: count, dtype: int64

### Cleaning and EDA

#### Some things to check
* Why is there a discrepancy between scraped records and successful records? - DONE
* Does each player have an AIFF ID? The ones that don't have an AIFF ID will have to be dropped. - DONE
* Check aiff_id and player_id differences - DONE
* For the entries where one_team_player_data_missing = True, do you drop them? - DONE
* Does each AIFF ID have one player attached to it? The ones which have more than one need to be checked. - DONE
* Does each player map to one team? The players mapping to multiple teams need to be checked. - DONE
* Confirm meaning of status and type - DONE
* check if competition_id and competition_name correspond 1:1 (one id can't have multiple names and vice versa)
* check dates format - DONE
* check if team_type is always == 2 - DONE

#### Why is there a discrepancy between scraped records and successful records?

In [10]:
print(f"Unique matches scraped successfully: {len(records)}")
print(f"Unique match IDs in data frame created out of successfully scraped matches: {len(player_matches['match_id'].value_counts())}")
print(f"Difference in successfully scraped records and data frame of successfully scraped records: {len(records) - len(player_matches['match_id'].value_counts())}")
# 25301 attempted. 21027 matches scraped successfully. 18205 remained in dataframe at player-match level due to missing both team's player information in 2822 matches.

Unique matches scraped successfully: 21027
Unique match IDs in data frame created out of successfully scraped matches: 18205
Difference in successfully scraped records and data frame of successfully scraped records: 2822

In [11]:
# Is it that the matches with no player data are responsible for the discrepancy in match counts? As player_match dataset created by looping over combined player lists from both teams in a match, where both teams have missing player data, those matches won't be accounted for.abs

both_missing = 0
one_missing = 0
neither_missing = 0

for record in records:
    t1 = record.get("team1_players", [])
    t2 = record.get("team2_players", [])

    t1_empty = len(t1) == 0
    t2_empty = len(t2) == 0

    if t1_empty and t2_empty:
        both_missing += 1
    elif t1_empty or t2_empty:
        one_missing += 1
    else:
        neither_missing += 1

print(f"Both team player lists missing: {both_missing} matches have both team players list empty")
print(f"Only one team player list missing: {one_missing} matches have one team players list empty")
print(f"Neither team player list missing: {neither_missing} matches have both team players list filled")
print(f"Total records checked: {both_missing + one_missing + neither_missing}")
# so it is clear that the matches that got dropped when created data frame from scraped records are the ones which don't have player data in them. While these matches may contain player information in the squad fields, squad data cannot be used as a substitute because it does not reliably distinguish the matchday lineup, substitutes, and players who actually appeared.

Both team player lists missing: 2822 matches have both team players list empty
Only one team player list missing: 669 matches have one team players list empty
Neither team player list missing: 17536 matches have both team players list filled
Total records checked: 21027

In [12]:
df_analysis['one_team_player_data_missing'].value_counts()

one_team_player_data_missing
False    284748
True       7096
Name: count, dtype: int64

* Out of the successfully scraped 21027 records, 13% of the records (2822) did not have player information and so had to be dropped. 
* So, about 13% of successfully scraped matches lack player-level data.
* A further 669 matches contain player data for only one team. These matches are naturally retained in the data frame, but players from the team with missing data are necessarily excluded, potentially leading to an undercount of appearances for those players.
* If this analysis is pursued for publication, it will be important to determine whether the missingness is concentrated in particular competitions or broadly distributed across the 
dataset, and whether it could systematically bias the final results. Squad lists were not used to backfill missing player lists because they did not provide the identifiers needed to link players reliably to substitution events. Treating squad-list inclusion as an appearance would risk counting unused or non-playing squad members and therefore overestimating player appearances.

#### Are there missing values for key fields?

In [13]:
# What are the fields?
df_analysis.columns
# we definitely need player_aiff_id, match_date, team_type and status

Index(['match_id', 'competition_id', 'competition_name', 'match_date',
       'match_venue', 'match_stadium', 'ft', 'ft_text', 'team_type',
       'player_name', 'player_id', 'player_aiff_id', 'player_team_id',
       'status', 'one_team_player_data_missing', 'substituted', 'team_name',
       'AI_level', 'AI_state', 'AI_age', 'AI_primary_format_teams',
       'AI_gender'],
      dtype='str')

In [14]:
# Count missing values in every column

missing_values = (
    df_analysis
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print(missing_values)

match_stadium                   123031
match_id                             0
player_team_id                       0
AI_primary_format_teams              0
AI_age                               0
AI_state                             0
AI_level                             0
team_name                            0
substituted                          0
one_team_player_data_missing         0
status                               0
player_aiff_id                       0
competition_id                       0
player_id                            0
player_name                          0
team_type                            0
ft_text                              0
ft                                   0
match_venue                          0
match_date                           0
competition_name                     0
AI_gender                            0
dtype: int64

* The only field containing missing values is match_stadium. As stadium information is not used in the appearance analysis, these missing values do not affect the analytical dataset.
* All player rows contain a non-missing AIFF ID; no rows need to be excluded on this basis.

#### Does each AIFF ID have one player attached to it? The ones which have more than one need to be checked.

In [15]:
# checking # of players per id 
unique_players_per_id = df_analysis.groupby("player_aiff_id")["player_name"].nunique().sort_values(ascending=False)
unique_players_per_id
# so multiple unique player names are attached to one player aiff id

player_aiff_id
342710    4
292057    4
209747    4
304215    3
208503    3
         ..
325619    1
325523    1
325492    1
325490    1
529901    1
Name: player_name, Length: 29568, dtype: int64

In [16]:
# checkign only for entries where player per id > 1 
more_than_one_player_per_aiff_id = unique_players_per_id[unique_players_per_id>1]
more_than_one_player_per_aiff_id
with pd.option_context("display.max_rows", None): #display all rows
    display(more_than_one_player_per_aiff_id)

player_aiff_id
342710    4
292057    4
209747    4
304215    3
208503    3
207089    3
172869    3
388844    3
381593    3
341727    3
389980    3
296143    3
285400    3
208546    3
255778    3
254474    3
360113    3
268886    3
285247    3
269068    3
253772    3
253756    3
262391    3
208547    3
253692    3
209819    3
171227    3
210442    3
171109    3
370625    3
211180    3
171417    3
171435    3
289278    3
187694    3
278857    3
212273    3
209748    3
385038    3
385157    3
171803    3
289860    3
171877    3
214273    3
253723    3
187687    3
187986    3
346151    3
187312    3
186751    3
187321    3
285166    3
186441    3
188221    3
284670    3
284398    3
284751    3
284752    3
189777    3
284176    3
187477    3
352761    3
351995    3
413037    3
393981    3
171801    2
171606    2
171649    2
171881    2
410785    2
171879    2
187552    2
171878    2
171827    2
187539    2
171806    2
171807    2
171601    2
171813    2
171816    2
182879    2
171556    2
171594    2
171458    2
187653    2
187635    2
187626    2
171230    2
171352    2
187593    2
187588    2
171453    2
171460    2
187575    2
171465    2
171467    2
187584    2
171534    2
187583    2
171900    2
171592    2
187579    2
378979    2
382960    2
171941    2
272342    2
176254    2
379648    2
381490    2
381465    2
177978    2
274428    2
274330    2
274282    2
380929    2
380820    2
187481    2
273478    2
380297    2
380290    2
183323    2
183295    2
182143    2
183290    2
183264    2
273168    2
176240    2
186587    2
171174    2
411093    2
187378    2
187372    2
380073    2
171957    2
172023    2
172033    2
172058    2
275530    2
172253    2
172340    2
172345    2
172367    2
382630    2
172818    2
172956    2
173844    2
175988    2
187320    2
176227    2
171214    2
48902     2
171173    2
388912    2
284187    2
284134    2
284030    2
284027    2
283949    2
283929    2
283348    2
302698    2
302708    2
144021    2
283109    2
283098    2
283014    2
283009    2
283008    2
144342    2
144726    2
145334    2
390747    2
146260    2
282436    2
282356    2
146542    2
390244    2
304258    2
284190    2
284193    2
141396    2
284655    2
284918    2
132176    2
284896    2
284892    2
284884    2
284754    2
284727    2
453960    2
137424    2
284722    2
284700    2
284649    2
284251    2
284641    2
284577    2
465082    2
300217    2
139100    2
140217    2
284352    2
284305    2
140580    2
140962    2
141004    2
469453    2
388874    2
171172    2
388829    2
161808    2
162103    2
162111    2
162232    2
385878    2
162242    2
162243    2
162268    2
162981    2
479204    2
513252    2
163271    2
480273    2
384148    2
167291    2
480631    2
168853    2
383907    2
383808    2
309538    2
170173    2
170452    2
171104    2
171105    2
171115    2
386746    2
161795    2
386755    2
159948    2
305271    2
388508    2
157607    2
280760    2
448538    2
158142    2
158225    2
388096    2
159881    2
280359    2
387932    2
159951    2
475548    2
160051    2
160184    2
160288    2
160299    2
387717    2
160325    2
279487    2
387384    2
387355    2
409556    2
387208    2
165432    2
189130    2
187701    2
215176    2
215191    2
262266    2
262186    2
435662    2
489821    2
489898    2
489932    2
217961    2
218824    2
490042    2
219049    2
334224    2
336637    2
220832    2
260299    2
223157    2
338409    2
225906    2
227831    2
362253    2
362085    2
423307    2
361961    2
361936    2
498090    2
215180    2
215063    2
255775    2
366942    2
417717    2
369603    2
212431    2
212510    2
212519    2
325575    2
326188    2
212957    2
213223    2
213237    2
488822    2
263403    2
368730    2
368711    2
368610    2
213576    2
213578    2
213730    2
327196    2
214325    2
214458    2
214528    2
367352    2
214881    2
366975    2
229691    2
230065    2
187763    2
496586    2
496449    2
236905    2
236906    2
430458    2
356258    2
349783    2
248589    2
350178    2
239436    2
426895    2
247484    2
495499    2
241253    2
353928    2
427483    2
495239    2
351812    2
353156    2
246137    2
353071    2
353006    2
352166    2
352823    2
352793    2
352581    2
425876    2
492387    2
433046    2
492384    2
361004    2
343852    2
360781    2
344168    2
231800    2
231823    2
254232    2
232669    2
497361    2
497357    2
497351    2
253762    2
253700    2
253699    2
253698    2
253673    2
359514    2
359482    2
359459    2
345450    2
252650    2
496756    2
358587    2
492381    2
492383    2
325216    2
264022    2
212179    2
413159    2
195663    2
318133    2
375834    2
268909    2
318988    2
413932    2
268470    2
201428    2
374723    2
374696    2
203310    2
374599    2
203619    2
203635    2
203699    2
204500    2
267706    2
267705    2
204683    2
205119    2
373640    2
414726    2
414753    2
320713    2
439677    2
413166    2
376802    2
212173    2
194673    2
187771    2
187832    2
378503    2
378494    2
187963    2
188038    2
188413    2
188563    2
188683    2
188793    2
188798    2
188982    2
271083    2
131810    2
189252    2
189534    2
189540    2
190068    2
316693    2
378001    2
377990    2
190301    2
190828    2
192402    2
317677    2
373126    2
415048    2
207283    2
207541    2
209761    2
209836    2
370908    2
323500    2
210031    2
210050    2
210087    2
210145    2
210150    2
210219    2
210241    2
210278    2
210371    2
210378    2
416429    2
265075    2
210921    2
211065    2
211230    2
211452    2
437259    2
264567    2
211674    2
211710    2
369981    2
209759    2
265482    2
209721    2
208719    2
207542    2
415372    2
266457    2
208252    2
415389    2
208489    2
208496    2
208564    2
208567    2
415512    2
208690    2
208892    2
209497    2
208977    2
209005    2
209220    2
209226    2
323119    2
209262    2
323162    2
209295    2
209312    2
415888    2
209420    2
131821    2
269180    2
294831    2
294243    2
285193    2
459271    2
459280    2
97856     2
287597    2
117464    2
98057     2
286200    2
289469    2
77055     2
90818     2
396021    2
98659     2
289829    2
285183    2
460139    2
287032    2
287774    2
56789     2
116337    2
291028    2
292829    2
455550    2
457560    2
56793     2
403146    2
286321    2
296154    2
116633    2
56798     2
286250    2
462291    2
102656    2
98140     2
285634    2
285367    2
462555    2
396611    2
405356    2
98159     2
117896    2
82431     2
291350    2
460205    2
405397    2
459326    2
290279    2
401413    2
461241    2
456322    2
458167    2
289425    2
90442     2
460181    2
459377    2
293252    2
49943     2
289456    2
291393    2
291897    2
103455    2
289428    2
460184    2
77480     2
285417    2
398721    2
98432     2
106976    2
286354    2
291270    2
290172    2
395283    2
112584    2
459417    2
401636    2
397337    2
455084    2
286641    2
98689     2
290142    2
289637    2
285575    2
289583    2
99084     2
291541    2
298078    2
285075    2
285017    2
397367    2
99219     2
460128    2
462253    2
459806    2
457171    2
67845     2
287925    2
Name: player_name, dtype: int64

In [17]:
# getting # of IDs for which repetition occurs 
more_than_one_player_per_aiff_id.value_counts().sort_index()

player_name
2    529
3     62
4      3
Name: count, dtype: int64

* 539 AIFF IDs have 2 players attached to them.
* 62 AIFF IDs have 3 players attached to them.
* 3 AIFF IDs have 4 players attached to them.

In [18]:
# inspecting the repetitions 
aiff_id_name_check = (
    df_analysis[
        df_analysis["player_aiff_id"].isin(more_than_one_player_per_aiff_id.index)
    ]
    .groupby("player_aiff_id")["player_name"]
    .agg(lambda x: sorted(x.unique()))
    .reset_index(name="player_names")
)

pd.set_option("display.max_colwidth", None)
aiff_id_name_check.head(30)

,player_aiff_id,player_names
0,48902,"[Rayaan Shakeer, Rayaan Shakeer (loc)]"
1,49943,"[Ahan Gupta, Ahan Gupta (loc)]"
2,56789,"[Sarath Rajkumar (loc), Sarath Rajkumar (u23)]"
3,56793,"[Essa Mohamed Yenepoya, Essa Mohamed Yenepoya (loc)]"
4,56798,"[Vignesh Vinod, Vignesh Vinod (loc)]"
5,67845,"[Prasanna Swaminathan, Prasanna Swaminathan (loc)]"
6,77055,"[Yohann Victor Britto, Yohann Victor Britto (loc)]"
7,77480,"[Mallikjan Kalegar, Mallikjan Kalegar (u23)]"
8,82431,"[Udit G, Udit G (loc)]"
9,90442,"[Sujay S (loc), Sujay S (u23)]"
10,90818,"[Bennet B Babu, Bennet B Babu (loc)]"
11,97856,"[Jomon Jacob, Jomon Jacob (non-local)]"
12,98057,"[Arif Khan, Arif Khan(pass) (loc)]"
13,98140,"[Utkarsh Narayan, Utkarsh Narayan (loc)]"
14,98159,"[Snehith Suresh, Snehith Suresh(pass)]"
15,98432,"[Ishan Roberts, Ishan Roberts (loc)]"
16,98659,"[Aryan A, Aryan A (loc)]"
17,98689,"[Liam Terence Fernandes, Liam Terence Fernandes (local)]"
18,99084,"[Shivansh Raina, Shivansh Raina (loc)]"
19,99219,"[Derron Austin Sumesh, Derron Austin Sumesh (local)]"
20,102656,"[Sachin R, Sachin R(loc)]"
21,103455,"[Saikhom Abinash Singh, Saikhom Abinash Singh (nl)]"
22,106976,"[B P Aniket, B P Aniket (loc)]"
23,112584,"[Surya Ragish, Surya Ragish (loc)]"
24,116337,"[Daksh Malhotra, Daksh Malhotra (non-local)]"
25,116633,"[Khuraijam Rishikanta Singh, Khuraijam Rishikanta Singh (nl)]"
26,117464,"[K Madan Kumar, K Madan Kumar (loc)]"
27,117896,"[Mohamed Safwaan, Mohamed Safwaan (non-local)]"
28,131810,"[Aakansh, Aakansh (loc)]"
29,131821,"[Nukala Nehal Sri Vital (loc), Nukala Nehal Sri Vital (loc) (p)]"

In [19]:
# checking what bracket text usually contains 
bracket_text = (
    df_analysis["player_name"]
    .str.extract(r"\(([^()]*)\)", expand=False)
    .str.strip()
    .str.lower()
)

bracket_text.value_counts(dropna=False)

player_name
NaN                     271414
loc                      14687
.                         4328
non-loc                    633
non-local                  182
l                          178
nl                          73
local                       67
pass                        63
p                           58
u23                         45
u-23                        30
non- loc                    16
                            15
osp                         11
*                            9
fail                         7
not eligible anymore         6
non local                    5
5 match ban                  5
pundalik                     4
non- local                   2
f                            2
na                           2
lc                           1
ineligible                   1
Name: count, dtype: int64

In [20]:
# checking pundalik: can we just remove (pundalik)?
df_analysis[
    df_analysis["player_name"].str.contains(
        r"\(pundalik\)",
        case=False,
        regex=True,
        na=False
    )
][["player_aiff_id", "player_name"]]

        player_aiff_id                     player_name
92631           409571  Nihal (pundalik) Nilesh Shetye
213073          409571  Nihal (pundalik) Nilesh Shetye
213163          409571  Nihal (pundalik) Nilesh Shetye
213251          409571  Nihal (pundalik) Nilesh Shetye

In [21]:
# Remove administrative annotations from player names and standardize formatting.
# Note: '(pundalik)' is intentionally preserved (if we remove it, we could remove important name identifiers).

import re

annotations_to_remove = [
    ".",
    "loc",
    "local",
    "l",
    "lc",
    "nl",
    "non-loc",
    "non-local",
    "non- loc",
    "non local",
    "non- local",
    "pass",
    "p",
    "u23",
    "u-23",
    "osp",
    "*",
    "fail",
    "not eligible anymore",
    "5 match ban",
    "f",
    "na",
    "ineligible",
]

annotation_pattern = "|".join(
    re.escape(annotation) for annotation in annotations_to_remove
)

df_analysis["player_name_clean"] = (
    df_analysis["player_name"]
    # Remove specified annotations when enclosed in parentheses.
    .str.replace(
        rf"\s*\(\s*(?:{annotation_pattern})\s*\)",
        "",
        regex=True,
        flags=re.IGNORECASE,
    )
    # Remove trailing administrative labels not enclosed in parentheses.
    .str.replace(
        r"\s*-?\s*(?:p|loc|nl|non-local|pass)\s*$",
        "",
        regex=True,
        case=False,
    )
    # Remove trailing punctuation.
    .str.replace(r"[\s.\-*]+$", "", regex=True)
    # Standardize whitespace.
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [22]:
# checkign only for entries where player per id > 1 again
unique_players_per_id = df_analysis.groupby("player_aiff_id")["player_name_clean"].nunique().sort_values(ascending=False)
more_than_one_player_per_aiff_id = unique_players_per_id[unique_players_per_id>1]
more_than_one_player_per_aiff_id.value_counts().sort_index()
# now only 32 aiff id's have 2 player names attached to them.

player_name_clean
2    32
Name: count, dtype: int64

In [62]:
# inspecting the repetitions 
aiff_id_name_check = (
    df_analysis[
        df_analysis["player_aiff_id"].isin(more_than_one_player_per_aiff_id.index)
    ]
    .groupby("player_aiff_id")["player_name_clean"]
    .agg(lambda x: sorted(x.unique()))
    .reset_index(name="player_names")
)

pd.set_option("display.max_colwidth", None)
aiff_id_name_check.head(100)

Empty DataFrame
Columns: [player_aiff_id, player_names]
Index: []

In [24]:
# dealing with non-standardized name discrepancies: for each listed player_aiff_id, use this one standardized name

player_name_corrections = {
    132176: "Jess Sanjay Bhobe", #every row with player_aiff_id == 132176 should have player_name_clean changed to "Jess Sanjay Bhobe".
    162111: "Wangkheirakpam Punshiba Meetei",
    170173: "Muhamad Anas U R",
    177978: "Houlungou Mate",
    212431: "Tanishq Harshal Pandya",
    214458: "Devanandhan K S",
    239436: "Lalremruatfela R",
    246137: "Chetan Konthoujam Singh",
    248339: "Prisha Bhairav Patel",
    264022: "Trishan Naskar",
    265482: "Abhisekh Mahato",
    275530: "Raja Baidya",
    284251: "Devyaan Anand Shah",
    284751: "Vihaan Pandey",
    284754: "Ch Sakip",
    289637: "Marshal Murmu",
    289860: "Dhaanya Harshit Desai",
    323162: "Ahamed Kaaf Bin Firos",
    323500: "Mehtab Singh",
    325216: "Faizal Hussain",
    325575: "Ajilesh S Babu",
    362253: "Nishant Mangesh Tawade",
    382630: "Martin Janggoulen Khongsai",
    409556: "Mahendra Prakash Naik",
    410785: "Sawan Jha",
    425876: "Sayan Mondal",
    426895: "Maxwell Vailan Silva",
    430458: "Shashwat Kamboj",
    430887: "Reya Rakesh Kumar Maharajwala",
    433733: "Pahal Nabin Agarwal",
    439677: "Bikram Lohra",
    475548: "Soham Tiwari",
    513252: "Gulshan Kh Singha",
    491665: "Damanpreet Kaur",
}

# apply the corrections 
df_analysis["player_name_clean"] = (
    df_analysis["player_aiff_id"]
    .map(player_name_corrections)
    .fillna(df_analysis["player_name_clean"]) #where there is no manual correction, retain the existing cleaned name.
)

In [25]:
# checkign only for entries where player per id > 1 again
unique_players_per_id = df_analysis.groupby("player_aiff_id")["player_name_clean"].nunique().sort_values(ascending=False)
more_than_one_player_per_aiff_id = unique_players_per_id[unique_players_per_id>1]
more_than_one_player_per_aiff_id.value_counts().sort_index()

player_name_clean
2    2
Name: count, dtype: int64

In [26]:
# inspecting the repetitions 
aiff_id_name_check = (
    df_analysis[
        df_analysis["player_aiff_id"].isin(more_than_one_player_per_aiff_id.index)
    ]
    .groupby("player_aiff_id")["player_name_clean"]
    .agg(lambda x: sorted(x.unique()))
    .reset_index(name="player_names")
)
aiff_id_name_check

   player_aiff_id                    player_names
0          208690  [Kiyan Lalwani, Vansh Lalwani]
1          401413      [Yash Dhaval, Yash Sharma]

In [27]:
# is player id also the same for these? 
df_analysis[
    df_analysis["player_aiff_id"].isin([208690, 401413])
][[
    "player_aiff_id",
    "player_id",
    "player_name",
    "player_team_id",
    "competition_name",
    "match_date"
]].sort_values(
    ["player_aiff_id", "match_date"]
)
# seems like a data entry errors. player_id different, aiff id attached same by mistake.

,player_aiff_id,player_id,player_name,player_team_id,competition_name,match_date
497102,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"01 February 2026,"
465274,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"02 April 2026,"
464657,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"02 February 2026,"
296329,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"02 November 2025,"
514606,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"03 April 2026,"
465038,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"04 April 2026,"
409800,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"04 January 2026,"
514806,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"05 April 2026,"
252974,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"05 October 2025,"
465573,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"07 April 2026,"
506405,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"08 February 2026,"
563583,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"08 March 2026,"
464347,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"09 April 2026,"
308043,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"09 November 2025,"
464169,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"10 April 2026,"
464497,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"11 February 2026,"
442354,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"11 January 2026,"
260518,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"12 October 2025,"
464804,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"13 February 2026,"
376312,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"14 December 2025,"
515598,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"15 February 2026,"
465345,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"16 February 2026,"
316395,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"16 November 2025,"
455875,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"18 January 2026,"
466126,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"20 February 2026,"
390323,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"21 December 2025,"
231245,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"21 September 2025,"
526896,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"22 February 2026,"
352051,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"23 November 2025,"
404936,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"28 December 2025,"
465681,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"28 February 2026,"
465884,208690,396223,Kiyan Lalwani,14440,AIFF Sub Junior League 2025-26,"30 March 2026,"
361082,208690,399897,Vansh Lalwani,14440,GUJARAT SFA (U-15) BOYS YOUTH LEAGUE - 2025-26,"30 November 2025,"
357884,401413,413668,Yash Sharma,12361,AIFF Sub Junior League 2025-26,"02 December 2025,"
357817,401413,413668,Yash Sharma,12361,AIFF Sub Junior League 2025-26,"06 December 2025,"
506842,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"07 February 2026,"
561556,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"07 March 2026,"
622427,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"12 April 2026,"
574813,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"14 March 2026,"
518978,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"15 February 2026,"
645512,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"18 April 2026,"
333389,401413,413668,Yash Sharma,12361,AIFF Sub Junior League 2025-26,"20 November 2025,"
591133,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"22 March 2026,"
333457,401413,413668,Yash Sharma,12361,AIFF Sub Junior League 2025-26,"22 November 2025,"
658395,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"23 April 2026,"
658488,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"26 April 2026,"
546098,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"28 February 2026,"
591244,401413,445711,Yash Dhaval (loc),12361,KSFA Youth Premier League Junior Tier-1 (U-15) 2025-26,"28 March 2026,"

In [28]:
# Create a cleaned player identifier, initially identical to the original AIFF ID.
df_analysis["player_aiff_id_cleaned"] = (
    df_analysis["player_aiff_id"].astype(str)
)

# AIFF IDs manually verified to refer to two different players.
collision_ids = [208690, 401413]

# Identify rows corresponding to these conflicting AIFF IDs.
mask = df_analysis["player_aiff_id"].isin(collision_ids)

# For conflicting cases, append player_id to create unique player identifiers
# (e.g. 208690_396223 and 208690_399897).
df_analysis.loc[mask, "player_aiff_id_cleaned"] = ( #CREATING NEW VARIABLE PLAYER_AIFF_ID_CLEANED
    df_analysis.loc[mask, "player_aiff_id"].astype(str)
    + "_"
    + df_analysis.loc[mask, "player_id"].astype(str)
)

# Examples:
# 208690 → 208690_396223 (Kiyan Lalwani), 208690_399897 (Vansh Lalwani)
# 401413 → 401413_413668 (Yash Sharma), 401413_445711 (Yash Dhaval)

In [29]:
# checkign only for entries where player per id > 1 again
unique_players_per_id = df_analysis.groupby("player_aiff_id_cleaned")["player_name_clean"].nunique().sort_values(ascending=False)
more_than_one_player_per_aiff_id = unique_players_per_id[unique_players_per_id>1]
more_than_one_player_per_aiff_id.value_counts().sort_index()
# done!

Series([], Name: count, dtype: int64)

#### Check if competition_id and competition_name correspond 1:1 (one id can't have multiple names and vice versa)

In [30]:
competition_names_per_id = (
    df_analysis
    .groupby("competition_id")["competition_name"] # how many names attached to one competition id?
    .nunique() #how many unique names attached to one competition id?
)

competition_ids_with_multiple_names = (
    competition_names_per_id[
        competition_names_per_id > 1
    ]
)

print(
    f"Competition IDs with multiple names: "
    f"{len(competition_ids_with_multiple_names)}"
)

print(competition_names_per_id)

Competition IDs with multiple names: 0
competition_id
1014    1
1139    1
1140    1
1141    1
1203    1
       ..
2096    1
2097    1
2098    1
2112    1
2130    1
Name: competition_name, Length: 90, dtype: int64

In [31]:
# checking the reverse 
competition_ids_per_name = (
    df_analysis
    .groupby("competition_name")["competition_id"]
    .nunique()
)

competition_names_with_multiple_ids = (
    competition_ids_per_name[
        competition_ids_per_name > 1
    ]
)

print(
    f"Competition names with multiple IDs: "
    f"{len(competition_names_with_multiple_ids)}"
)

Competition names with multiple IDs: 0

* Competition name and IDs map 1:1 with each other. Competition IDs and competition names correspond one-to-one; no ID is associated with multiple names, and no name is associated with multiple IDs.

#### Does each player map to one team? The players mapping to multiple teams within the same competition / match need to be checked. (Note that multiple teams across all competitions is expected)

In [32]:
# count how many teams each player is associated with
teams_per_player = (
    df_analysis
    .groupby("player_aiff_id_cleaned")["team_name"]
    .nunique()
)

players_with_multiple_teams = (
    teams_per_player[
        teams_per_player > 1
    ]
)
print(
    f"Players associated with multiple teams: "
    f"{len(players_with_multiple_teams)}"
)

Players associated with multiple teams: 2031

In [33]:
player_team_check = (
    df_analysis[
        df_analysis["player_aiff_id_cleaned"].isin(
            players_with_multiple_teams.index
        )
    ]
    .groupby("player_aiff_id_cleaned")
    .agg(
        player_names=("player_name_clean", lambda x: sorted(x.unique())),
        teams=("team_name", lambda x: sorted(x.unique())),
    )
    .reset_index()
)

with pd.option_context(
    "display.max_rows", None,
    "display.max_colwidth", None,
):
    display(player_team_check)
#a player can show up for multiple teams. the inconsistency will be when they show up for multiple teams within the same competition/league!

,player_aiff_id_cleaned,player_names,teams
0,102656,[Sachin R],"[Kickstart FC Karnataka, Mahesh Raj United FC Bangalore]"
1,103455,[Saikhom Abinash Singh],"[Mahesh Raj United FC Bangalore, Sporting Club Delhi]"
2,105110,[Manjot Singh],"[FC Goa, Punjab FC]"
3,105384,[Alan Saji],"[FC Goa, Sporting Club Delhi]"
4,112584,[Surya Ragish],"[Alchemy International FA, Roots Football Club]"
5,115654,[Thangjam Roshan Singh],"[CLASSIC FOOTBALL ACADEMY, Mohun Bagan Super Giant]"
6,116337,[Daksh Malhotra],"[Maharashtra Oranje FC, Roots Football Club]"
7,116456,[Saish Gaunkar],"[FC Goa, SESA Football Academy]"
8,116633,[Khuraijam Rishikanta Singh],"[Kickstart FC Karnataka, Rajasthan United Football Club]"
9,117205,[Lalthangliana],"[Diamond Harbour Football Club, FC Goa]"
10,117475,[Sahrudai Vaddi],"[Roots Football Club, Sreenidi Deccan Football Club]"
11,117885,[Kyle Gaspar],"[Bidesh XI Sports Club, Sporting Clube de Goa ]"
12,117896,[Mohamed Safwaan],"[Roots Football Club, South United FC]"
13,118790,[Arjun Singh Rawat],"[Ahbab Football Club, Conscient Football]"
14,119417,[Aayan Maldar],"[Chapora Yuvak Sangh, Sporting Clube de Goa ]"
15,122289,[Raunak Viswas Volvoikar],"[Geno FC, Penha De France Sports Club]"
16,123355,[Pallujam Rohan Singh],"[Jamshedpur FC, Mohun Bagan Super Giant]"
17,130000,[Anik Das],"[Bhawanipore FC, SP ONE FOUNDATION]"
18,130009,[Rahul Kashya],"[Corbett FC, Sudeva Delhi FC]"
19,130450,[Debayudh Das],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, NATAGARGH FRIENDS ASSOCIATION]"
20,130984,[Hridaan D Metha],"[Ignite Football Club Pune , Oscar Foundation- Mumbai]"
21,131641,[Atharvan Naidu],"[BLG- THE DIAMOND ROCK F.C., STEMFIELD FOOTBALL CLUB JABALPUR]"
22,131821,[Nukala Nehal Sri Vital],"[Playsmart Football Club, Young Blues Elite FC]"
23,132176,[Jess Sanjay Bhobe],"[Mumbai City FC, SESA Football Academy]"
24,137497,[Lemmet Tangvah],"[FC Goa, Rajasthan United Football Club]"
25,137719,[Maibam Hanjaba Meitei],"[ARA FC, Corbett FC]"
26,138190,[Ngamchinlen Kilong],"[Mohun Bagan Super Giant, SADAR HILLS FA]"
27,138572,[Chesam Imran Khan],"[Alchemy International FA, PFC Kerala]"
28,139100,[Dhanush Urs],"[Roots Football Club, Young Blues Elite FC]"
29,140423,[Pardeep Singh],"[Punjab FC, Sri Dashmesh Martial Sports Academy]"
30,140580,[Shijin S],"[Kickstart FC Karnataka, SAI Centre, Kollam]"
31,141004,[Vaishak A],"[Alchemy International FA, FC Real Bengaluru ]"
32,141226,[James Thongmin Chongloi],"[Chennaiyin FC, East Bengal FC]"
33,141396,[Euhan K Kuruvilla],"[FC Real Bengaluru , South United FC]"
34,141505,[Achouba Huidrom],"[Chennaiyin FC, Mohun Bagan Super Giant]"
35,142135,[Raj Mandrekar],"[Chapora Yuvak Sangh, Sporting Clube de Goa ]"
36,143002,[Muhammed Zahan M.m],"[North East United FC, Sreenidi Deccan Football Club]"
37,143128,[Miran Kaping],"[Alchemy International FA, North East United FC]"
38,143532,[Moirangthem Marjit Singh],"[Diamond Harbour Football Club, Jamshedpur FC]"
39,143900,[Adrita Mahato],"[Diamond Harbour Football Club, Mohun Bagan Super Giant]"
40,143937,[Gingoungam Hmangte],"[East Bengal FC, Punjab FC]"
41,143942,[Kowshick Refi S],"[FC Tamilions, Kickstart FC Karnataka]"
42,144021,[Mallhar Shah],"[FC Real Bengaluru , GMSC]"
43,144042,[Karan Makkar],"[East Bengal FC, Jamshedpur FC]"
44,144207,[Sri Aniket Biswas],"[Mohun Bagan Super Giant, South United FC]"
45,144656,[Md Adnan],"[FOOTBALL 4 CHANGE ACADEMY, Jamshedpur FC]"
46,144660,[Ankit Choudhary],"[Chennaiyin FC, Kerala Blasters Football Club]"
47,144891,[Tanbir Dey],"[BENGAL FOOTBALL ACADEMY, North East United FC]"
48,145010,[Jasiel Mascarenhas],"[Geno FC, Penha De France Sports Club]"
49,145121,[Bivan Jyoti Laskar],"[Jamshedpur FC, Mohun Bagan Super Giant]"
50,146542,[Vaibhav Ramesh],"[PFC Kerala, William Soccer Academy]"
51,146737,[Nihar Nalesh Naik],"[Cortalim Villagers Social Welfare Sports Club, Dempo Sports Club]"
52,146777,[Mohammad Hussain Totad],"[Clube De Salgaocar, Dempo Sports Club]"
53,146916,[Shavir Ahmed],"[Calangute Association, Penha De France Sports Club]"
54,147172,[Vishal S M],"[LITTLE FLOWER FOOTBALL ACADEMY, SAI Centre, Kollam]"
55,147494,[Abhishek Boro],"[Gauhati Town Club, Kaziranga Football Academy]"
56,150376,[Serto Worneilen Kom],"[Bengaluru Football Club, Mohun Bagan Super Giant]"
57,154863,[Ahshash Nirwan],"[Corbett FC, The Sports School]"
58,156560,[Md Arbash],"[Bengaluru Football Club, CLASSIC FOOTBALL ACADEMY]"
59,156561,[Bharat Lairenjam],"[CLASSIC FOOTBALL ACADEMY, Mohun Bagan Super Giant]"
60,156579,[Yaipharemba Chingakham],"[Bengaluru Football Club, CLASSIC FOOTBALL ACADEMY]"
61,156599,[Aheibam Suraj Singh],"[Bengaluru Football Club, CLASSIC FOOTBALL ACADEMY]"
62,156659,[Punit Thangjam],"[CLASSIC FOOTBALL ACADEMY, Mohun Bagan Super Giant]"
63,156660,[Ahongshangbam Samson],"[Bengaluru Football Club, CLASSIC FOOTBALL ACADEMY]"
64,156668,[Mutum Anish Singh],"[CLASSIC FOOTBALL ACADEMY, East Bengal FC]"
65,156850,[Ningthoukhongjam Rishi Singh],"[Bengaluru Football Club, CLASSIC FOOTBALL ACADEMY]"
66,156888,[Amzard Khan],"[Diamond Harbour Football Club, Jamshedpur FC]"
67,157105,[Laishram Suraj Singh],"[Alchemy International FA, Chennaiyin FC]"
68,157632,[Potshangbam Abinash Singh],"[Alchemy International FA, Chennaiyin FC]"
69,158008,[Tejas Arun Kamat],"[Dempo Sports Club, Dempo Sports Club (JRS)]"
70,158011,[Fayaz Ahmed Lathewale],"[Clube De Salgaocar, Sirlim Sports Club]"
71,158015,[Sohan Joe Fernandes],"[Ave Maria Athletic & Walkers Club, United Sports Club Of Seraulim]"
72,158026,[Desiderio Kiefer Barreto],"[Salcete Football Club, Sirlim Sports Club]"
73,158225,[Abhinav Srikanth],"[The Sports School, Young Blues Elite FC]"
74,158959,[Souradip Pramanick],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, SOUTH DUMDUM MUNICIPAL SPORTS ACADEMY]"
75,159207,[Rohith Samivelu],"[Chennaiyin FC, FC Tamilions]"
76,159447,[Anirvinya Sarkar],"[Basmat City Football Club - Hingoli, Hungry Hearts Soccer School]"
77,160055,[Money Kalia],"[Delhi Football Club, Himachal FC]"
78,160105,[Showmik Dey],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, Panihati Fashion Zone Football Academy]"
79,160184,[Nikhil Srinivas],"[The Sports School, Young Blues Elite FC]"
80,160531,[Granville Fernandes],"[Guardian Angel Sports Club, SESA Football Academy]"
81,160543,[Jaedon Dias],"[Snow’s Football Academy, South Goa United Club of Sports & Culture ]"
82,160556,[Wayne Stalin Colaco],"[FC Goa, Snow’s Football Academy]"
83,160566,[Modan Rai],"[Numaligarh Refinery Limited Football Academy, Salbari Rebels United FC]"
84,161188,[Alfy Joju],"[New Football Club Kerala, PFC Kerala]"
85,161597,[Zaim Abdulla C H],"[Malabar Football Club, Snipers Football Club]"
86,162075,[Sk Saifuluddin],"[ASOS Rainbow Athletic Club, Adamas United Sports Academy]"
87,162100,[Md Jayed],"[Himachal FC, Techtro Swades United FC]"
88,162101,[Ningombam Shrinivas Singh],"[Minerva Academy FC, Rajasthan United Football Club]"
89,162103,[Ishan Saikia],"[Alchemy International FA, FC Madras]"
90,162196,[Pritam Gain],"[East Bengal FC, Mohun Bagan Super Giant]"
91,162232,[Rehaan Rai],"[Bangalore City FC, Roots Football Club]"
92,162242,[Shreshta Chandrashekar Poojari],"[Bangalore City FC, Roots Football Club]"
93,162607,[Ehshan],"[Noida City FC, Northern United Football Club, Sudeva Delhi FC]"
94,162893,[Lalgousem Tuboi],"[FOOTBALL 4 CHANGE ACADEMY, Punjab FC]"
95,162928,[Shubh Shekhar Kerkar],"[FC Goa, Sporting Clube de Goa ]"
96,162931,[Adamas Prestigius Pereira],"[Santa Cruz Club of Cavelossim, Sirlim Sports Club, Sporting Clube de Goa ]"
97,162933,[Jonathan Jose Silva],"[Dempo Sports Club, Dempo Sports Club (JRS)]"
98,163972,[Samuel Onthanglen Haoki],"[East Bengal FC, Punjab FC]"
99,164032,[Ankit Chakraborty],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, Bhawanipore FC]"
100,164359,[Althaf Rahiman],"[Gokulam Kerala FC, Malabar Football Club]"
101,165432,[Aamayr Singh],"[South United FC, William Soccer Academy]"
102,167291,[Harshavardhan Pawar],"[Alchemy International FA, FC Real Bengaluru ]"
103,169077,[Jinesh Thoudam],"[AIFF Bhubaneswar Academy, SP FOOTBALL ACADEMY ]"
104,170121,[Levin Stanly],"[Kerala Blasters Football Club, Sportto Soccer Club]"
105,171105,[Adityavardhan Jha],"[The Sports School, Young Blues Elite FC]"
106,171227,[Vivaan Agarwal],"[The Sports School, Young Blues Elite FC]"
107,171284,[Ishaan Jagota Mittal],"[Dempo Sports Club, South United FC]"
108,171352,[Arnav Raghavan],"[Alchemy International FA, The Sports School]"
109,171435,[Samridh K Prabhu],"[The Sports School, Young Blues Elite FC]"
110,171465,[Rakshit P Anil],"[Bengaluru Football Club, Raman Sports Academy]"
111,171594,[Dhanush P Jamadagni],"[Bengaluru Football Club, Young Blues Elite FC]"
112,171601,[Lakshith B J],"[Football Club Mangalore, Kickstart FC Karnataka]"
113,171649,[Pranav K R],"[Bhaichung Bhutia Football Schools- Bengaluru, Raman Sports Academy]"
114,171654,[Elroy Jacob Elvis],"[The Sports School, Young Blues Elite FC]"
115,171877,[Neil Nandigam],"[Alchemy International FA, Bengaluru Football Club]"
116,172014,[Ridit Maheshwari],"[Roots Football Club, Young Blues Elite FC]"
117,172023,[Arth Chandramoorthy],"[Bangalore City FC, Kickstart FC Karnataka]"
118,172367,[Allen Joshua],"[The Sports School, Young Blues Elite FC]"
119,172734,[Haodamlian Vaiphei],"[Kerala Blasters Football Club, Mohun Bagan Super Giant]"
120,172816,[Udayan Prabhuram],"[AIFF FIFA Talent Academy, Odisha, FC Madras]"
121,173536,[Shougaijam Yohenba Singh],"[Punjab FC, TYDA]"
122,173903,[Vivek Dey],"[Guwahati City Football Club, North East United FC]"
123,173951,[Ningthoujam Remson Singh],"[Jamshedpur FC, Mohun Bagan Super Giant]"
124,174104,[Rian Uniyal],"[Mumbai City FC, SSE BFC Soccer Schools, Mumbai]"
125,174411,[Yuki Singh Laishram],"[ARA FC, Corbett FC]"
126,175988,[Rishab Pradhan],"[Roots Football Club, SESA Football Academy]"
127,176215,[Ved Thakkar],"[ARA FC, FC Madras]"
128,176227,[Anirudh D],"[The Sports School, Young Blues Elite FC]"
129,177406,[Flexson Gomes],"[Guardian Angel Sports Club, Panchwadi United Sports Club]"
130,177745,[Elangbam Nestanboy Singh],"[Rajasthan United Football Club, TYDA]"
131,178414,[Joseph Peter],"[New Football Club Kerala, Sportto Soccer Club]"
132,178792,[Ningthoujam Barun],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
133,180099,[Takhellambam Bobbish],"[Bengaluru Football Club, Corbett FC]"
134,180155,[Md Aryan Khan],"[Juba Sangha FC, Punjab Sporting FA]"
135,181121,[Meghash F],"[LITTLE FLOWER FOOTBALL ACADEMY, South United FC]"
136,181967,[Henlenmang Chongloi],"[Kerala Blasters Football Club, SADAR HILLS FA]"
137,182143,[Mowneesh R],"[Bhaichung Bhutia Football Schools- Bengaluru, Dream Big Soccer School India, Karur]"
138,182199,[A Sunil],"[Kickstart FC Karnataka, Puzhal Football Coaching Association]"
139,182420,[Atharva Suvarnsingh Rane],"[Dempo Sports Club, Football Club Tuem]"
140,182427,[Taranveer Singh],"[Sri Dashmesh Martial Sports Academy, Sudeva Delhi FC]"
141,183290,[Rowan James],"[FC Real Bengaluru , South United FC]"
142,183295,[Havish Chalke],"[Football Club Mangalore, Kickstart FC Karnataka]"
143,186310,[Mrigasya Biswas],"[Himachal FC, Raman Sports Academy]"
144,187321,[Pranav A],"[The Sports School, Young Blues Elite FC]"
145,187372,[Naradulla Akshat Reddy],"[The Sports School, Young Blues Elite FC]"
146,187460,[Janglawmka],"[Lenruol Football Club, PEHLUM LAMHIL LAWM]"
147,187477,[Hamdan Hussain Shaik],"[Bengaluru Football Club, The Sports School]"
148,187539,[Sikandar M],"[Mahesh Raj United FC Bangalore, Roots Football Club]"
149,187552,[Ishan Roy Chowdhury],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
150,187579,[Kian Suresh],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
151,187583,[Tejas Vikram],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
152,187584,[Sam Joe Saiju],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
153,187588,[Ryan Abraham Mathew],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
154,187593,[Vivaan S Tegginmani],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
155,187626,[Ojas Maheshkumar Katkar],"[Kickstart FC Karnataka, VIVA FOOTBALL ACADEMY- Pune]"
156,187694,[Abhijeet Gopinath],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
157,187701,[Shaan Abraham Lobo],"[Roots Football Club, Young Blues Elite FC]"
158,187703,[Gagan Jayarama Reddy],"[Alchemy International FA, Roots Football Club]"
159,187771,[Nived Pankaj Menon],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
160,187832,[Himaghna Sanyal],"[Inter Kashi, Young Blues Elite FC]"
161,187986,[S Monish],"[The Sports School, Young Blues Elite FC]"
162,188063,[Kartik Singh],"[Corbett FC, Sudeva Delhi FC]"
163,188221,[Ashith Sanjay Dyapi],"[The Sports School, Young Blues Elite FC]"
164,188563,[Moses K Zochhuanmauwia],"[FC Real Bengaluru , Roots Football Club]"
165,188617,[Takhellambam Bungson Singh],"[Bengaluru Football Club, CLASSIC FOOTBALL ACADEMY]"
166,189534,[Joel Johnson V],"[Bangalore City FC, Bengaluru Football Club]"
167,189707,[Brahmacharimayum Sumit Sharma],"[CLASSIC FOOTBALL ACADEMY, Kerala Blasters Football Club]"
168,191134,[Thingom Somokanta Singh],"[ASUFII FA, TYDA]"
169,192456,[Tanishq Panicker],"[Community Football Club India , VASAI VIRAR UNITED FOOTBALL ASSOCIATION]"
170,192979,[Boss Thongbam Meitei],"[Alchemy International FA, North East United FC]"
171,193341,[Ujjwal Banerjee],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, Panihati Fashion Zone Football Academy]"
172,193343,[Azizul Molla],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, Panihati Fashion Zone Football Academy]"
173,193378,[Abhideep Naskar],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, Bhawanipore FC]"
174,193390,[Sayan Saha],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, Panihati Fashion Zone Football Academy]"
175,193514,[Deb Sarkar],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, Panihati Fashion Zone Football Academy]"
176,193518,[Oyshik Ray Chowdhury],"[East Bengal FC, Mohun Bagan Super Giant]"
177,193569,[Bhola Rajwar],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, East Bengal FC]"
178,193576,[Rudranil Saha],"[BENGAL FOOTBALL ACADEMY, East Bengal FC]"
179,193770,[Jangminlun Kipgen],"[FOOTBALL 4 CHANGE ACADEMY, LAMKA FA]"
180,194168,[Sagolsem Anish Singh],"[Alchemy International FA, North East United FC]"
181,194713,[Omar Abdulla],"[Kerala Blasters Football Club, PFC Kerala]"
182,195490,[Arjun],"[Punjab FC, Rajasthan United Football Club]"
183,195539,[Sakiul Mondal],"[Mohammedan Sporting Club, Zinc Football Academy]"
184,195748,[Kanishk Rambhia],"[Learn to Play Football Academy- Thane, Sporting Club de Thane ]"
185,195896,[Jermey Bijoy],"[Bengaluru Football Club, Muthoot Football Academy]"
186,196457,[Sarvesh Yadav],"[Learn to Play Football Academy- Thane, MUM - Dsouza Football Academy]"
187,196491,[Aryan Pingale],"[Mumbai City FC, Rudra FC]"
188,196493,[Laksh Naresh Malkar],"[Mumbai City FC, Rudra FC]"
189,196968,[Thiyam Famous],"[AIFF FIFA Talent Academy, Odisha, Techtro Swades United FC]"
190,197211,[Nishad Sherigar],"[Learn to Play Football Academy- Thane, Sporting Club de Thane ]"
191,197871,[Waikhom Santomani Singh],"[Himachal FC, Techtro Swades United FC]"
192,197996,[Leo Thongbam],"[AIFF Bhubaneswar Academy, AIFF FIFA Talent Academy, Odisha]"
193,198826,[Juvenio Simoes],"[Dempo Sports Club, Dempo Sports Club (JRS)]"
194,199862,[Md Anaz Molla],"[BENGAL FOOTBALL ACADEMY, NATAGARGH FRIENDS ASSOCIATION]"
195,200017,[Rohit Roy],"[SKM SPORTS FOUNDATION (KALNA), SOUTH DUMDUM MUNICIPAL SPORTS ACADEMY]"
196,200599,[Govind Narayan Pandey],"[Ahbab Football Club, Juba Sangha FC]"
197,200930,[Krutik Gaikwad],"[Calangute Association, Dempo Sports Club]"
198,201399,[Ngamkhanlen Tuboi],"[Minerva Academy FC, Techtro Lucknow FC]"
199,201422,[Albert Khangembam],"[Minerva Academy FC, Techtro Lucknow FC]"
200,201428,[Lalvanghao Haoki],"[Himachal FC, MINERVA ACADEMY FC BENGALURU]"
201,201703,[Mohammad Saud Samdani],"[Alchemy International FA, Bangalore City FC]"
202,202413,[Yungam Neri],"[North East United FC, Zinc Football Academy]"
203,202770,[Ayan Das],"[City Football Club, United Sports Club]"
204,202994,[Maibam Hendik Singh],"[AIFF FIFA Talent Academy, Odisha, YOUTH SOCIAL WELFARE ASSOCIATION]"
205,203619,[Wahengbam Nibash Meetei],"[AIFF FIFA Talent Academy, Odisha, Alchemy International FA]"
206,203635,[Mutum Biky Meitei],"[Belgaum United Football Academy, Bengaluru Football Club]"
207,203704,[Dennish Thokchom],"[AIFF FIFA Talent Academy, Odisha, Alchemy International FA]"
208,203955,[Arnav Patil],"[AIFF FIFA Talent Academy, Telangana, FC Madras]"
209,204500,[Karthi S],"[Bengaluru International Football Academy, Roots Football Club]"
210,205304,[Tathagat Anuj Eleswarapu],"[Bravo Football, Mumbai City FC]"
211,205392,[Mohammed Sinan Mk],"[AIFF Bhubaneswar Academy, Muthoot Football Academy]"
212,205635,[Sonu Kumar],"[BIDHANNAGAR MUNICIPAL SPORTS ACADEMY, Panihati Fashion Zone Football Academy]"
213,205755,[Eshaan Naveenchandra Hegde],"[Buldana Football Academy, Rising Pune F.C.]"
214,205768,[Vedant Ajay Gupta],"[Roots Football Club, The Sports School]"
215,206312,[Debadrita Roy],"[Jyotirmoy Football Academy , Mohammedan Sporting Club]"
216,206342,[Haogoulun Singson],"[Bangalore City FC, Kickstart FC Karnataka]"
217,206470,[Neil Alby Mathew],"[Mumbai City FC, SSE BFC Soccer Schools, Mumbai]"
218,206505,[Ayush Koul],"[Mumbai City FC, Punjab FC]"
219,207089,[Abhyukt Choudhury],"[Alchemy International FA, Bengaluru Football Club]"
220,207508,[Gaurang Surve],"[The Soccer Academy, VASAI VIRAR UNITED FOOTBALL ASSOCIATION]"
221,207753,[Tanush Gaurav Goal],"[Community Football Club India , Reliance Foundation Young Champs]"
222,207981,[Mahit V Raj],"[Kickstart FC Karnataka, PFC Kerala]"
223,208143,[Arman Ahmad],"[Sreenidi Deccan Football Club, Sudeva Delhi FC]"
224,208154,[Ishaan Nandkishor Varpe],"[Buldana Football Academy, Rising Pune F.C.]"
225,208252,[Yatharth S Sawanth],"[Bengaluru International Football Academy, South United FC]"
226,208368,[Surajuddin Mondal],"[LUCKNOW FALCONS FOOTBALL CLUB, Panihati Fashion Zone Football Academy]"
227,208489,[K Aathan Ramasamy],"[Bengaluru Football Club, FC Madras]"
228,208627,[Lamminlen Chongloi],"[Dream Big Soccer School India, Karur, FOOTBALL 4 CHANGE ACADEMY]"
229,208861,[H K Adhi],"[DYES, South United FC]"
230,208892,[Nishaad Noah Malakar],"[Bhaichung Bhutia Football Schools- Bengaluru, The Sports School, Young Blues Elite FC]"
231,208977,[Neil Madhav S],"[Bhaichung Bhutia Football Schools- Bengaluru, The Sports School]"
232,208998,[Zidan Harun Pareed],"[Bhaichung Bhutia Football Schools- Bengaluru, Muthoot Football Academy]"
233,209007,[Arnav Singh],"[Mumbai City FC, SSE BFC Soccer Schools, Mumbai]"
234,209131,[Aadhinath A],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
235,209145,[Muhammed Fousan],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
236,209295,[B Abhiram],"[Roots Football Club, South United FC]"
237,209721,[Adithya Vijay],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
238,209742,[Gautam Uday Chavan],"[Rising Pune F.C., Sports Mania]"
239,209748,[Josh Paul Jyothish Cherian],"[Kickstart FC Karnataka, Raman Sports Academy]"
240,209759,[Chethan V Gowda],"[Kickstart FC Karnataka, Stadium Football Club]"
241,209761,[Sohan S],"[Roots Football Club, South United FC]"
242,209819,[Angad Singh],"[The Sports School, Young Blues Elite FC]"
243,209821,[Hridhaan Pawar],"[Mumbai City FC, SSE BFC Soccer Schools, Mumbai]"
244,209836,[Arvindh C],"[Bhaichung Bhutia Football Schools- Bengaluru, The Sports School]"
245,210020,[Antony Joe],"[Kerala Blasters Football Club, Muthoot Football Academy]"
246,210050,[Joe Tom Paracka],"[Bhaichung Bhutia Football Schools- Bengaluru, Snipers Football Club]"
247,210219,[Liam Christopher Lamb],"[Bengaluru Football Club, The Sports School]"

In [34]:
# Does a player appear for multiple team IDs within the same competition
teams_per_player_competition = (
    df_analysis
    .groupby(
        ["player_aiff_id_cleaned", "competition_id"]
    )["team_name"]
    .nunique()
)

player_competition_conflicts = (
    teams_per_player_competition[
        teams_per_player_competition > 1
    ]
)

print(
    "Player-competition combinations with multiple team names: "
    f"{len(player_competition_conflicts)}"
)

Player-competition combinations with multiple team names: 2

In [35]:
conflict_rows = (
    df_analysis
    .set_index(["player_aiff_id_cleaned", "competition_id"])
    .loc[player_competition_conflicts.index]
    .reset_index()
)

conflict_rows = conflict_rows.sort_values(
    ["player_name", "competition_name", "match_date"]
)

conflict_rows

,player_aiff_id_cleaned,competition_id,match_id,competition_name,match_date,match_venue,match_stadium,ft,ft_text,team_type,...,status,one_team_player_data_missing,substituted,team_name,AI_level,AI_state,AI_age,AI_primary_format_teams,AI_gender,player_name_clean
12,387210,1781,63026,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"01 February 2026,","ARA FC, AHMEDABAD",,True,This match has finished,2,...,3,False,False,NAVRACHANA SPORTS ACADEMY,State,Gujarat,Youth,Club League,Male,Krishiv Swamy
16,387210,1781,64632,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"01 March 2026,","BARODA FA, VADODARA",,True,This match has finished,2,...,3,False,False,NAVRACHANA SPORTS ACADEMY,State,Gujarat,Youth,Club League,Male,Krishiv Swamy
3,387210,1781,57948,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"02 November 2025,","BARODA FA, VADODARA",,True,This match has finished,2,...,1,False,False,"RANGER FOOTBALL ACADEMY, BARODA",State,Gujarat,Youth,Club League,Male,Krishiv Swamy
9,387210,1781,60720,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"04 January 2026,","ARA FC, AHMEDABAD",,True,This match has finished,2,...,1,False,False,NAVRACHANA SPORTS ACADEMY,State,Gujarat,Youth,Club League,Male,Krishiv Swamy
1,387210,1781,56854,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"05 October 2025,","BARODA FA, VADODARA",,True,This match has finished,2,...,1,False,False,"RANGER FOOTBALL ACADEMY, BARODA",State,Gujarat,Youth,Club League,Male,Krishiv Swamy
7,387210,1781,59709,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"07 December 2025,","BARODA FA, VADODARA",,True,This match has finished,2,...,1,False,False,"RANGER FOOTBALL ACADEMY, BARODA",State,Gujarat,Youth,Club League,Male,Krishiv Swamy
13,387210,1781,63247,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"08 February 2026,","BARODA FA, VADODARA",,True,This match has finished,2,...,3,False,False,NAVRACHANA SPORTS ACADEMY,State,Gujarat,Youth,Club League,Male,Krishiv Swamy
17,387210,1781,64834,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"08 March 2026,","BARODA FA, VADODARA",,True,This match has finished,2,...,3,False,False,NAVRACHANA SPORTS ACADEMY,State,Gujarat,Youth,Club League,Male,Krishiv Swamy
4,387210,1781,58139,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"09 November 2025,","BARODA FA, VADODARA",,True,This match has finished,2,...,1,False,False,"RANGER FOOTBALL ACADEMY, BARODA",State,Gujarat,Youth,Club League,Male,Krishiv Swamy
10,387210,1781,61523,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"11 January 2026,","BARODA FA, VADODARA",,True,This match has finished,2,...,3,False,False,NAVRACHANA SPORTS ACADEMY,State,Gujarat,Youth,Club League,Male,Krishiv Swamy
2,387210,1781,57012,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"12 October 2025,","BARODA FA, VADODARA",,True,This match has finished,2,...,1,False,False,"RANGER FOOTBALL ACADEMY, BARODA",State,Gujarat,Youth,Club League,Male,Krishiv Swamy
14,387210,1781,63461,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"15 February 2026,","ARA FC, AHMEDABAD",,True,This match has finished,2,...,3,False,False,NAVRACHANA SPORTS ACADEMY,State,Gujarat,Youth,Club League,Male,Krishiv Swamy
11,387210,1781,61846,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"18 January 2026,","ARA FC, AHMEDABAD",,True,This match has finished,2,...,3,False,False,NAVRACHANA SPORTS ACADEMY,State,Gujarat,Youth,Club League,Male,Krishiv Swamy
15,387210,1781,63792,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"22 February 2026,","ARA FC, AHMEDABAD",,True,This match has finished,2,...,3,False,False,NAVRACHANA SPORTS ACADEMY,State,Gujarat,Youth,Club League,Male,Krishiv Swamy
5,387210,1781,59263,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"23 November 2025,","BARODA FA, VADODARA",,True,This match has finished,2,...,1,False,False,"RANGER FOOTBALL ACADEMY, BARODA",State,Gujarat,Youth,Club League,Male,Krishiv Swamy
8,387210,1781,60625,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"28 December 2025,","BARODA FA, VADODARA",,True,This match has finished,2,...,1,False,False,NAVRACHANA SPORTS ACADEMY,State,Gujarat,Youth,Club League,Male,Krishiv Swamy
0,387210,1781,56605,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"28 September 2025,",VADODARA,,True,This match has finished,2,...,1,False,False,"RANGER FOOTBALL ACADEMY, BARODA",State,Gujarat,Youth,Club League,Male,Krishiv Swamy
6,387210,1781,59492,GUJARAT SFA (U-13) BOYS YOUTH LEAGUE - 2025-26,"30 November 2025,","KAHAANI FC, AHMEDABAD",,True,This match has finished,2,...,1,False,False,"RANGER FOOTBALL ACADEMY, BARODA",State,Gujarat,Youth,Club League,Male,Krishiv Swamy
18,430458,1430,52160,HP U-17 Men's YOUTH League 2025,"03 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
19,430458,1430,52161,HP U-17 Men's YOUTH League 2025,"06 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
20,430458,1430,52163,HP U-17 Men's YOUTH League 2025,"07 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
21,430458,1430,52165,HP U-17 Men's YOUTH League 2025,"09 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
22,430458,1430,52167,HP U-17 Men's YOUTH League 2025,"10 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
23,430458,1430,52169,HP U-17 Men's YOUTH League 2025,"12 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
24,430458,1430,52171,HP U-17 Men's YOUTH League 2025,"13 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
25,430458,1430,52173,HP U-17 Men's YOUTH League 2025,"15 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
35,430458,1430,52589,HP U-17 Men's YOUTH League 2025,"16 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
26,430458,1430,52177,HP U-17 Men's YOUTH League 2025,"18 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
28,430458,1430,52179,HP U-17 Men's YOUTH League 2025,"19 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
31,430458,1430,52181,HP U-17 Men's YOUTH League 2025,"21 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
32,430458,1430,52183,HP U-17 Men's YOUTH League 2025,"22 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
33,430458,1430,52184,HP U-17 Men's YOUTH League 2025,"24 April 2025,",NFL Nangal,,True,This match has finished,2,...,3,False,False,Techtro Swades United FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
27,430458,1430,52177,HP U-17 Men's YOUTH League 2025,"18 April 2025,",NFL Nangal,,True,This match has finished,2,...,2,False,False,Himachal FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
29,430458,1430,52180,HP U-17 Men's YOUTH League 2025,"19 April 2025,",NFL Nangal,,True,This match has finished,2,...,2,False,True,Himachal FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
30,430458,1430,52181,HP U-17 Men's YOUTH League 2025,"21 April 2025,",NFL Nangal,,True,This match has finished,2,...,2,False,False,Himachal FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj
34,430458,1430,52185,HP U-17 Men's YOUTH League 2025,"22 April 2025,",NFL Nangal,,True,This match has finished,2,...,2,False,True,Himachal FC,State,Himachal Pradesh,Youth,Club League,Male,Shashwat Kamboj

In [36]:
# confirming that shashwat is appearing for opposing teams (that the two teams he is seeming to appear for are actually opposing teams)
for record in records:
    fixture = record.get("fixture", {})

    if fixture.get("id") in [52177, 52181]:
        print({
            "match_id": fixture.get("id"),
            "team1_id": fixture.get("team1_id"),
            "team1_name": fixture.get("team1_name"),
            "team2_id": fixture.get("team2_id"),
            "team2_name": fixture.get("team2_name"),
        })

{'match_id': 52177, 'team1_id': 14340, 'team1_name': None, 'team2_id': 14369, 'team2_name': None}
{'match_id': 52181, 'team1_id': 14369, 'team1_name': None, 'team2_id': 14340, 'team2_name': None}

* Krishiv Swamy does not look especially problematic. He appears for team 12674 through November 30, 2025, then for team 14440 from December 28 onward. Because the change is sequential and there is no overlap, it could reflect a mid-season transfer or registration change. Keep the appearances under the same player unless another field indicates two different people.
* One player was removed because the same player identifier appeared for opposing teams in the same matches, indicating an unresolved inconsistency in the source data.

In [37]:
# Remove the player with conflicting team assignments within the same matches.
df_analysis = df_analysis[
    df_analysis["player_aiff_id_cleaned"] != "430458"
].copy()

In [38]:
# Multiple teams within the same match confirming
same_match_conflicts = (
    df_analysis
    .groupby(["player_aiff_id_cleaned", "match_id"])["team_name"]
    .nunique()
)

same_match_conflicts = same_match_conflicts[same_match_conflicts > 1]
same_match_conflicts

Series([], Name: team_name, dtype: int64)

#### Are values in status and type in line with our assumptions about those variables?

In [39]:
df_analysis['status'].value_counts()

status
1    132491
3     82972
2     74861
4       990
0       500
Name: count, dtype: int64

In [40]:
# what is status 0?
status_0 = df_analysis[df_analysis["status"] == 0]

status_0[
    [
        "match_id",
        "competition_name",
        "player_name",
        "team_name",
        "substituted",
    ]
].head(30)

,match_id,competition_name,player_name,team_name,substituted
9271,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Ritik Yadav,Penha De France Sports Club,False
9273,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Raunak Viswas Volvoikar,Penha De France Sports Club,False
9274,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Babu Hussain Sheikh,Penha De France Sports Club,False
9276,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Ananthkumar Laxman Lamani,Penha De France Sports Club,False
9280,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Tejas Nagvekar,Penha De France Sports Club,False
9284,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Hrutvik Rajendra Paryekar,Penha De France Sports Club,False
9285,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Kabeer Mulgund,Penha De France Sports Club,False
9286,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Mehfuz Halsi,Penha De France Sports Club,False
9288,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Gatikh Deepak Volvoikar,Penha De France Sports Club,False
9294,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Sai Rupesh Parab,Penha De France Sports Club,False
9295,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Mevy Mark Vales,FC Goa,False
9297,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Harsh Nagvenkar,FC Goa,False
9299,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Manjot Singh,FC Goa,False
9300,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Emmanuel Gama,FC Goa,False
9301,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Lemmet Tangvah,FC Goa,False
9302,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Messi Fernandes,FC Goa,False
9303,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Messi Rebello,FC Goa,False
9304,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Crossley Warren Dias,FC Goa,False
9306,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Bryson Dias,FC Goa,False
9307,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Likson Rebelo,FC Goa,False
9308,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Shawn Franxer Fernandes,FC Goa,False
9313,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Joybud Mesquita,FC Goa,False
9314,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Ruell Goes,FC Goa,False
9316,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Callum Fernandes,FC Goa,False
9318,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Gourav C Shetty,FC Goa,False
9319,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Trance Maven Fernandes,FC Goa,False
9321,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Gogocha Chungkham,FC Goa,False
9323,49272,GFA U-19 DIV 1 LEAGUE MENS 2024-25,Aaryav Pio Caetano Antonio Da Costa,FC Goa,False
213077,55258,GFA U-18 BOYS DIV II LEAGUE 2025-26,Rohit Talkar,Football Club Tuem,False
213094,55258,GFA U-18 BOYS DIV II LEAGUE 2025-26,Sagar Lamani,Arpora Sporting Club,False

In [41]:
status_0['match_id'].value_counts()

match_id
49272    28
60045    19
57426    18
60114    18
64648    18
63438    17
59049    16
59918    15
69040    15
60431    14
60797    14
63555    14
59197    13
57445    12
57448    12
61114    12
61146    12
61149    12
69133    12
61095    11
61116    11
67089    11
57437    10
63467     9
55260     8
58898     8
59986     8
69496     8
59048     7
60782     7
60815     7
61039     7
61111     7
58214     6
60789     6
60807     6
60812     6
67900     6
55258     5
55262     5
60786     5
66686     5
68955     5
55263     4
60776     4
57855     3
57858     3
61107     3
62281     3
55259     2
57446     2
57459     2
60120     2
60803     2
60810     2
61443     2
57968     1
Name: count, dtype: int64

In [42]:
# what is status 4?
status_4 = df_analysis[df_analysis["status"] ==4]

status_4[
    [
        "match_id",
        "competition_name",
        "player_name",
        "team_name",
        "substituted",
    ]
].head(30)

,match_id,competition_name,player_name,team_name,substituted
162,70599,R-LEAGUE YOUTH U13 (Boy's) 2025-26,Virendra Singh,Jaipur Elite Football Club,False
217,70601,R-LEAGUE YOUTH U13 (Boy's) 2025-26,Aryaveer Bhargava,Jaipur Futsal,False
10188,49293,Delhi Future Stars Youth League U-19 2024/25,Raj Kumar,The Dream Team,False
10985,49329,KSFA Youth Premier League U-17 Tier-1 2024-25,Paul Pradeep,Alchemy International FA,False
11055,49330,KSFA Youth Premier League U-17 Tier-1 2024-25,Tejas Vikram (loc),Bhaichung Bhutia Football Schools- Bengaluru,False
11063,49330,KSFA Youth Premier League U-17 Tier-1 2024-25,Arvindh C (loc),Bhaichung Bhutia Football Schools- Bengaluru,False
14377,49442,Delhi Future Stars Youth League U-17 2024/25,Shaunak Ganguly,Hindustan Football Club,False
18728,49650,Delhi Future Stars Youth League U-19 2024/25,Prince Verma,The Dream Team,False
20826,49719,AIFF Junior League 2024-25,Soibam Alex Singh,Belgaum United Football Academy,False
20870,49720,AIFF Junior League 2024-25,Siddhant Chiplunkar,Mumbai City FC,False
20876,49720,AIFF Junior League 2024-25,Ayush Koul,Mumbai City FC,False
20893,49721,AIFF Junior League 2024-25,Jobin,Kerala Blasters Football Club,False
20905,49721,AIFF Junior League 2024-25,Ajilesh Babu,Kerala Blasters Football Club,False
20974,49722,AIFF Junior League 2024-25,Rupam Seal,FC Madras,False
21408,49733,AIFF Sub Junior League 2024-25,Rupam Ghosh,East Bengal FC,False
21420,49733,AIFF Sub Junior League 2024-25,Mohammad Ahmad Wadoo,East Bengal FC,False
21504,49735,AIFF Sub Junior League 2024-25,Debraj Gayen,United Sports Club,False
23306,49780,KFA Youth League (U-17) 2024-25,Muhammed Binshan A,City Club Chalakudy,False
26030,49867,Delhi Future Stars Youth League U-17 2024/25,Aryamn Vibhor,Hindustan Football Club,False
26255,49873,Delhi Future Stars Youth League U-17 2024/25,Ishan Singh,Noida City FC,False
26284,49874,Delhi Future Stars Youth League U-17 2024/25,Atharv Sharma,Delhi Football Club,False
26449,49878,Delhi Future Stars Youth League U-17 2024/25,Khursheed Akbar,The Dream Team,False
33645,50109,Delhi Future Stars Youth League U-19 2024/25,Siddharth Pathak,Garhwal United Football Club,False
36089,50199,Delhi Future Stars Youth League U-19 2024/25,Sumit,Sudeva Delhi FC,False
36138,50201,Delhi Future Stars Youth League U-19 2024/25,Yumnam Daniel Singh,The Dream Team,False
36143,50201,Delhi Future Stars Youth League U-19 2024/25,Divyansh Pal Dhangar,Noida City FC,False
36556,50219,Delhi Future Stars Youth League U-19 2024/25,Jangminlal Haokip,Noida City FC,False
36621,50220,Delhi Future Stars Youth League U-19 2024/25,Mohd Sakib,Frontier Football Club Delhi,False
44713,50494,Delhi Future Stars Youth League U-13 2024/25,Ningthouujam Thoithoiba Meetei,Sudeva Delhi FC,False
44715,50494,Delhi Future Stars Youth League U-13 2024/25,Loitongbam Lenin Meitei,Sudeva Delhi FC,False

Status values 0,3, and 4 were observed only among players who neither started nor entered as substitutes, and were therefore treated as non-appearances. we don't know what the difference is, but for the purpose of the analysis, that difference is not relevant.

In [43]:
# now, confirming if our substituted status makes sense! my hypothesis is:
# Status 1: should never be marked as substituted (because they are starters, not entrants).
# Status 2: may or may not be substituted. Some bench players come on, many don't.
# Status 3: should never be substituted.
# Status 4: should never be substituted.
# Status 0: should never be substituted.
pd.crosstab(
    df_analysis["status"],
    df_analysis["substituted"],
    normalize="index"
).round(3)
# awesome!

substituted  False  True
status
0             1.00   0.00
1             1.00   0.00
2             0.55   0.45
3             1.00   0.00
4             1.00   0.00

In [44]:
df_analysis["appearance"] = (
    (df_analysis["status"] == 1)
    | (df_analysis["substituted"]) # appearance is true if you either started the match OR you came on later as a substitute. Note that match hours would differ!
)

In [45]:
# Only bench players should ever be flagged as substituted on 
df_analysis[
    (df_analysis["substituted"]) &
    (df_analysis["status"] != 2)
][
    ["match_id", "player_name", "status", "team_name"]
]

        match_id         player_name  status                        team_name
102973     52160       Vihaan Dhyani       1  Summerhill United Football Club
103085     52164       Vihaan Dhyani       1  Summerhill United Football Club
104991     52218        Kaushik Mani       1                          BPSS FC
104998     52218  Yohaan Philip Jose       1                          BPSS FC
494886     62972  Rajan Bhajo Lambor       1       Guardian Angel Sports Club
792729     71629         Gaurab Boro       1           Private Sports Academy

In [46]:
#seeing all rows with kaushik mani to confirm it doesn't impact our analysis even if 4 rows show that starter also was substitute
cols = [
    "match_id",
    "competition_name",
    "team_name",
    "player_name",
    "player_aiff_id",
    "status",
    "substituted",
    "appearance",
]

df_analysis.loc[
    df_analysis["player_name"].eq("Kaushik Mani"),
    cols
].sort_values("match_id")

,match_id,competition_name,team_name,player_name,player_aiff_id,status,substituted,appearance
86291,51705,KSFA Youth Premier League U-21 2024-25,BPSS FC,Kaushik Mani,179998,2,False,False
104991,52218,KSFA Youth Premier League U-21 2024-25,BPSS FC,Kaushik Mani,179998,1,True,True
112477,52453,KSFA Youth Premier League U-21 2024-25,BPSS FC,Kaushik Mani,179998,1,False,True
114331,52530,KSFA Youth Premier League U-21 2024-25,BPSS FC,Kaushik Mani,179998,1,False,True
116182,52574,KSFA Youth Premier League U-21 2024-25,BPSS FC,Kaushik Mani,179998,2,True,True

In [47]:
df_analysis.loc[
    df_analysis["player_aiff_id"] == 179998,
    "appearance"
].sum()
# returns 4, no over counting! so we can keep these rows.

np.int64(4)

* Internal consistency check: A small number of player-match records (6) were internally inconsistent, with the same player recorded both as a starter (status = 1) and as an incoming substitute (aiff_player_id in a substitution event). These records were retained because both indicators independently confirm that the player appeared in the match. Since the dataset contains one row per player per match and appearances were defined as (status == 1) OR (entered as a substitute), these inconsistencies did not result in double-counting. Manual validation confirmed that affected players were counted once per match.

In [48]:
# No starter should ever be flagged as substituted on
df_analysis[(df_analysis["status"] == 1) & (df_analysis["substituted"])]

,match_id,competition_id,competition_name,match_date,match_venue,match_stadium,ft,ft_text,team_type,player_name,...,substituted,team_name,AI_level,AI_state,AI_age,AI_primary_format_teams,AI_gender,player_name_clean,player_aiff_id_cleaned,appearance
102973,52160,1430,HP U-17 Men's YOUTH League 2025,"03 April 2025,",NFL Nangal,,True,This match has finished,2,Vihaan Dhyani,...,True,Summerhill United Football Club,State,Himachal Pradesh,Youth,Club League,Male,Vihaan Dhyani,447996,True
103085,52164,1430,HP U-17 Men's YOUTH League 2025,"07 April 2025,",NFL Nangal,,True,This match has finished,2,Vihaan Dhyani,...,True,Summerhill United Football Club,State,Himachal Pradesh,Youth,Club League,Male,Vihaan Dhyani,447996,True
104991,52218,1565,KSFA Youth Premier League U-21 2024-25,"28 May 2025,",Bangalore Football Stadium,,True,This match has finished,2,Kaushik Mani,...,True,BPSS FC,State,Karnataka,Youth,Club League,Male,Kaushik Mani,179998,True
104998,52218,1565,KSFA Youth Premier League U-21 2024-25,"28 May 2025,",Bangalore Football Stadium,,True,This match has finished,2,Yohaan Philip Jose,...,True,BPSS FC,State,Karnataka,Youth,Club League,Male,Yohaan Philip Jose,188401,True
494886,62972,1947,GFA U-16 BOYS DIV 1 LEAGUE 2025-26,"29 April 2026,",Sinquetim Sports Complex,,True,This match has finished,2,Rajan Bhajo Lambor,...,True,Guardian Angel Sports Club,State,Goa,Youth,Club League,Male,Rajan Bhajo Lambor,254199,True
792729,71629,2046,"Assam Youth League U-17, 2025-26","14 May 2026,",Changsari field,,True,This match has finished,2,Gaurab Boro,...,True,Private Sports Academy,State,Assam,Youth,Club League,Male,Gaurab Boro,526103,True

#### What is team_type?

In [49]:
df_analysis['team_type'].value_counts()

team_type
2    291814
Name: count, dtype: int64

In [50]:
df_analysis.loc[
    df_analysis["team_type"] == 1,
    "competition_name"
].drop_duplicates().sort_values()

Series([], Name: competition_name, dtype: str)

#### What is the date-time column looking like?

In [51]:
df_analysis.head(200)

,match_id,competition_id,competition_name,match_date,match_venue,match_stadium,ft,ft_text,team_type,player_name,...,substituted,team_name,AI_level,AI_state,AI_age,AI_primary_format_teams,AI_gender,player_name_clean,player_aiff_id_cleaned,appearance
0,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Kabir Mehta,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Kabir Mehta,418848,True
1,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Tavish Sharma,...,True,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Tavish Sharma,398082,True
2,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Eklavya Choudhary,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Eklavya Choudhary,522296,False
3,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Swastik Sharma,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Swastik Sharma,398260,True
4,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"19 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Navya Mittal,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Navya Mittal,418674,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,70601,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"21 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Naman Grover,...,False,Red Stone City Football Club,State,Rajasthan,Youth,Club League,Male,Naman Grover,528638,False
196,70601,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"21 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Trinay Mansinghka,...,False,Red Stone City Football Club,State,Rajasthan,Youth,Club League,Male,Trinay Mansinghka,425684,False
197,70601,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"21 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Raunak Pamnani,...,False,Red Stone City Football Club,State,Rajasthan,Youth,Club League,Male,Raunak Pamnani,406811,True
198,70601,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"21 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Sachin,...,False,Red Stone City Football Club,State,Rajasthan,Youth,Club League,Male,Sachin,528339,True
199,70601,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,"21 June 2026,",\nPoornima University,NaN,True,This match has finished,2,Karnik Gupta,...,False,Red Stone City Football Club,State,Rajasthan,Youth,Club League,Male,Karnik Gupta,527855,True

In [52]:
df_analysis["match_date"] = pd.to_datetime(
    df_analysis["match_date"],
    errors="coerce"
)

In [53]:
df_analysis["match_date"].isna().sum()

np.int64(0)

In [54]:
df_analysis.head(200)

,match_id,competition_id,competition_name,match_date,match_venue,match_stadium,ft,ft_text,team_type,player_name,...,substituted,team_name,AI_level,AI_state,AI_age,AI_primary_format_teams,AI_gender,player_name_clean,player_aiff_id_cleaned,appearance
0,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-19,\nPoornima University,NaN,True,This match has finished,2,Kabir Mehta,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Kabir Mehta,418848,True
1,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-19,\nPoornima University,NaN,True,This match has finished,2,Tavish Sharma,...,True,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Tavish Sharma,398082,True
2,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-19,\nPoornima University,NaN,True,This match has finished,2,Eklavya Choudhary,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Eklavya Choudhary,522296,False
3,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-19,\nPoornima University,NaN,True,This match has finished,2,Swastik Sharma,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Swastik Sharma,398260,True
4,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-19,\nPoornima University,NaN,True,This match has finished,2,Navya Mittal,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Navya Mittal,418674,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,70601,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-21,\nPoornima University,NaN,True,This match has finished,2,Naman Grover,...,False,Red Stone City Football Club,State,Rajasthan,Youth,Club League,Male,Naman Grover,528638,False
196,70601,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-21,\nPoornima University,NaN,True,This match has finished,2,Trinay Mansinghka,...,False,Red Stone City Football Club,State,Rajasthan,Youth,Club League,Male,Trinay Mansinghka,425684,False
197,70601,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-21,\nPoornima University,NaN,True,This match has finished,2,Raunak Pamnani,...,False,Red Stone City Football Club,State,Rajasthan,Youth,Club League,Male,Raunak Pamnani,406811,True
198,70601,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-21,\nPoornima University,NaN,True,This match has finished,2,Sachin,...,False,Red Stone City Football Club,State,Rajasthan,Youth,Club League,Male,Sachin,528339,True
199,70601,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-21,\nPoornima University,NaN,True,This match has finished,2,Karnik Gupta,...,False,Red Stone City Football Club,State,Rajasthan,Youth,Club League,Male,Karnik Gupta,527855,True

In [55]:
df_analysis["match_date"].agg(["min", "max"])
# the dataset starts from 11th October 2024 and ends on 7th July 2026.

min   2024-11-09
max   2026-07-07
Name: match_date, dtype: datetime64[us]

In [56]:
df_analysis["match_date"].dt.year.value_counts().sort_index()

match_date
2024      1738
2025    120254
2026    169822
Name: count, dtype: int64

In [57]:
#checking 2024 entries 
df_analysis.loc[
    df_analysis["match_date"].dt.year == 2024,
    ["competition_id", "competition_name", "match_date"]
].drop_duplicates().sort_values("match_date")

,competition_id,competition_name,match_date
67469,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-11-09
67742,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-11-10
67795,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-11-23
68093,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-11-24
68177,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-11-30
68383,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-12-01
68429,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-12-07
68565,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-12-08
94058,1254,GFA U-15 DIV 2 LEAGUE 2024-25,2024-12-11
68603,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-12-14
68823,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-12-15
93917,1254,GFA U-15 DIV 2 LEAGUE 2024-25,2024-12-18
68921,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-12-21
69109,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-12-22
69209,1204,KSFA Youth Premier League U-17 Tier-2 2024-25,2024-12-28

In [58]:
# make dataset of 2025 - 2026 season and save it for final analysis!

In [59]:
season_start = pd.Timestamp("2025-07-10")
season_end = pd.Timestamp("2026-05-31")

df_analysis_final = df_analysis[
    (df_analysis["match_date"] >= season_start) &
    (df_analysis["match_date"] <= season_end)
].copy()

In [67]:
len(df_analysis_final)

225993

In [61]:
df_analysis_final.to_csv("analysis_dataset.csv", index=False)

In [68]:
len(df_analysis)

291814

In [69]:
df_analysis

,match_id,competition_id,competition_name,match_date,match_venue,match_stadium,ft,ft_text,team_type,player_name,...,substituted,team_name,AI_level,AI_state,AI_age,AI_primary_format_teams,AI_gender,player_name_clean,player_aiff_id_cleaned,appearance
0,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-19,\nPoornima University,NaN,True,This match has finished,2,Kabir Mehta,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Kabir Mehta,418848,True
1,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-19,\nPoornima University,NaN,True,This match has finished,2,Tavish Sharma,...,True,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Tavish Sharma,398082,True
2,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-19,\nPoornima University,NaN,True,This match has finished,2,Eklavya Choudhary,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Eklavya Choudhary,522296,False
3,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-19,\nPoornima University,NaN,True,This match has finished,2,Swastik Sharma,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Swastik Sharma,398260,True
4,70600,2094,R-LEAGUE YOUTH U13 (Boy's) 2025-26,2026-06-19,\nPoornima University,NaN,True,This match has finished,2,Navya Mittal,...,False,Rajasthan Football School,State,Rajasthan,Youth,Club League,Male,Navya Mittal,418674,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
806269,72239,2044,"Assam Youth League U-15, 2025-26",2026-06-23,SAI field,,True,This match has finished,2,Jyotisman Boro,...,False,SAI Guwahati,State,Assam,Youth,Club League,Male,Jyotisman Boro,424377,False
806270,72239,2044,"Assam Youth League U-15, 2025-26",2026-06-23,SAI field,,True,This match has finished,2,Samir Basfor,...,False,SAI Guwahati,State,Assam,Youth,Club League,Male,Samir Basfor,472713,False
806271,72239,2044,"Assam Youth League U-15, 2025-26",2026-06-23,SAI field,,True,This match has finished,2,Arup Karmakar,...,False,SAI Guwahati,State,Assam,Youth,Club League,Male,Arup Karmakar,322854,False
806272,72239,2044,"Assam Youth League U-15, 2025-26",2026-06-23,SAI field,,True,This match has finished,2,Hintu Ray,...,False,SAI Guwahati,State,Assam,Youth,Club League,Male,Hintu Ray,467164,False
806273,72239,2044,"Assam Youth League U-15, 2025-26",2026-06-23,SAI field,,True,This match has finished,2,Alex Chetia,...,False,SAI Guwahati,State,Assam,Youth,Club League,Male,Alex Chetia,320324,True

In [73]:
df_analysis['AI_state'].value_counts()

AI_state
National            99871
West Bengal         31052
Goa                 29007
Maharashtra         24854
Karnataka           22811
Gujarat             16875
Delhi               12956
Kerala              11931
Rajasthan           10368
Himachal Pradesh     9250
Puducherry           7645
Assam                6886
Madhya Pradesh       2843
Punjab               1694
Chhattisgarh         1382
Odisha               1319
Manipur              1029
Tamil Nadu             41
Name: count, dtype: int64

In [77]:
club_players = (
    df_analysis[df_analysis["appearance"]]
    .groupby("team_name")
    .agg(
        players_appeared=("player_aiff_id_cleaned", "nunique")
    )
    .sort_values("players_appeared", ascending=False)
    .reset_index()
)
pd.set_option("display.max_rows", None)
club_players.head(100)

                                        team_name  players_appeared
0                        Alchemy International FA               239
1                          Kickstart FC Karnataka               208
2                                      PFC Kerala               182
3                              United Sports Club               174
4                                  East Bengal FC               172
5            BIDHANNAGAR MUNICIPAL SPORTS ACADEMY               161
6                   Kerala Blasters Football Club               161
7                             Roots Football Club               154
8                                  Bhawanipore FC               150
9                                 South United FC               147
10                                Sudeva Delhi FC               144
11                           Raman Sports Academy               144
12                  Northern United Football Club               136
13                        Mohun Bagan Super Giant               135
14                            Delhi Football Club               133
15                  SKM SPORTS FOUNDATION (KALNA)               133
16                 Rajasthan United Football Club               133
17                      Churchill Brothers FC Goa               133
18                        Football Club Mangalore               130
19                      FOOTBALL 4 CHANGE ACADEMY               125
20                           SPORTING CLUB KERALA               125
21         Panihati Fashion Zone Football Academy               120
22                        Bengaluru Football Club               119
23                       Muthoot Football Academy               117
24                 Community Football Club India                117
25                        BENGAL FOOTBALL ACADEMY               116
26                                      Punjab FC               114
27                     Snigmay Pune Football Club               112
28                            Sportto Soccer Club               111
29                                   Sporthood FC               110
30   Altius International Football Academy - AIFA               109
31                          SESA Football Academy               109
32                         Sporting Clube de Goa                108
33                              Dempo Sports Club               106
34                               Rising Pune F.C.               104
35               Reliance Foundation Young Champs               103
36                                  90 Minutes FC               102
37                       New Football Club Kerala               102
38                             Conscient Football               101
39                             Adrenaline New Era               100
40                         MADEN FOOTBALL ACADEMY               100
41                                   Sports Mania               100
42                            Don Bosco Vaduthala                99
43                                         ARA FC                98
44                                    Himachal FC                98
45                                         FC Goa                98
46                                     Corbett FC                97
47                    Jyotirmoy Football Academy                 96
48                              R&R Football Club                95
49                           Young Blues Elite FC                94
50                   Adamas United Sports Academy                93
51           Jaipur Boys & Girls Football Academy                93
52                                   Himalayan FC                92
53                KFTC Football Academy Kozhikode                92
54  KESHAB- UMA CHARITABLE TRUST FOOTBALL ACADEMY                90
55                        Hindustan Football Club                89
56                           Ashoka Football Club                89
57                                      ASUFII FA                88
58                          Maharashtra Oranje FC                87
59                       Matua United Sports Club                87
60                           North East United FC                87
61                  Sreenidi Deccan Football Club                87
62     South Goa United Club of Sports & Culture                 87
63                       Mohammedan Sporting Club                86
64          SOUTH DUMDUM MUNICIPAL SPORTS ACADEMY                85
65                                    MERLIN RISE                85
66                             Clube De Salgaocar                83
67                 SSE BFC Soccer Schools, Mumbai                83
68                          LFP FOOTBALL ACADEMIE                82
69                          Snipers Football Club                82
70                              The Sports School                82
71                        Baroda Football Academy                81
72                        Signature Football Club                81
73                              Gokulam Kerala FC                81
74                                  Jaipur Futsal                81
75                             Vels Football Club                80
76                             Shillong Lajong FC                80
77                       CLASSIC FOOTBALL ACADEMY                80
78                         DREAM FOOTBALL ACADEMY                79
79                            PUNE-UKM Kothrud FC                79
80                                  Noida City FC                79
81                                      FC Madras                79
82                   Savvy Swaraaj FC, Ahmedabad                 78
83           Dream Big Soccer School India, Karur                78
84                             PEHLUM LAMHIL LAWM                78
85                          Bidesh XI Sports Club                77
86                                 Juba Sangha FC                77
87                                      Thadam FC                77
88                                       LAMKA FA                77
89                             Minerva Academy FC                77
90                     Guardian Angel Sports Club                77
91                           RKM FOOTBALL ACADEMY                77
92                                Hooghly City FC                77
93                       Pax of Nagoa Sports Club                77
94                                  Jamshedpur FC                76
95       Bhaichung Bhutia Football Schools- Delhi                75
96                              SP ONE FOUNDATION                75
97                                    Inter Kashi                74
98                          Zinc Football Academy                74
99              Ave Maria Athletic & Walkers Club                72